Object.assign(recipes, {
  "poolish-donuts": {
    title: "波兰种甜甜圈",
    name: "Poolish Custard Donuts",
    image: "../images/poolish-donuts.jpeg",
    imagePosition: "center 60%",
    imageZoom: 1,
    intro: "松软的波兰种甜甜圈裹上细砂糖，再挤入顺滑香草卡仕达酱。",
    ingredients: [
      { type: "heading", text: "波兰种" },
      { name: "甜甜圈波兰种高筋面粉", displayName: "高筋面粉", amount: 50, unit: "g" },
      { name: "甜甜圈波兰种水", displayName: "水", amount: 50, unit: "g" },
      { name: "甜甜圈波兰种干酵母", displayName: "干酵母", amount: 0.7, unit: "g" },
      { name: "甜甜圈波兰种糖", displayName: "糖", amount: 7, unit: "g" },

      { type: "heading", text: "主面团" },
      { name: "甜甜圈高筋面粉", displayName: "高筋面粉", amount: 150, unit: "g" },
      { name: "甜甜圈低筋面粉", displayName: "低筋面粉", amount: 50, unit: "g" },
      { name: "甜甜圈牛奶", displayName: "牛奶", amount: 55, unit: "g" },
      { name: "甜甜圈奶粉", displayName: "奶粉", amount: 10, unit: "g" },
      { name: "甜甜圈盐", displayName: "盐", amount: 3, unit: "g" },
      { name: "甜甜圈糖", displayName: "糖", amount: 30, unit: "g" },
      { name: "甜甜圈干酵母", displayName: "干酵母", amount: 2, unit: "g" },
      { name: "甜甜圈全蛋", displayName: "全蛋", amount: 1, unit: "pc" },
      { name: "甜甜圈黄油", displayName: "黄油", amount: 25, unit: "g" },

      { type: "heading", text: "卡仕达酱" },
      { name: "卡仕达蛋黄", displayName: "蛋黄", amount: 3, unit: "pc" },
      { name: "卡仕达糖", displayName: "糖", amount: 50, unit: "g" },
      { name: "卡仕达玉米淀粉", displayName: "玉米淀粉", amount: 25, unit: "g" },
      { name: "卡仕达牛奶", displayName: "牛奶", amount: 300, unit: "g" },
      { name: "卡仕达香草膏", displayName: "香草膏", amount: 3, unit: "g" }
    ],
    steps: [
      "【卡仕达酱】",
      "{卡仕达蛋黄} 蛋黄、{卡仕达糖} 糖和 {卡仕达香草膏} 香草膏用蛋抽搅拌至发白。",
      "筛入 {卡仕达玉米淀粉} 玉米淀粉。",
      "{卡仕达牛奶} 牛奶加热至冒小泡，少量多次倒入蛋黄糊中。",
      "混合均匀后倒回锅中，小火加热并不断搅拌至浓稠。",
      "冒泡后关火，拌入少量黄油。",
      "盛出后用保鲜膜贴面覆盖，冷藏备用。",

      "【面团】",
      "将 {甜甜圈波兰种高筋面粉} 高筋面粉、{甜甜圈波兰种水} 水、{甜甜圈波兰种干酵母} 干酵母和 {甜甜圈波兰种糖} 糖混合均匀。",
      "室温或冷藏发酵至表面有许多气泡，里面呈蜂窝状。",
      "波兰种与除 {甜甜圈黄油} 黄油外的所有主面团材料混合，1 档揉成团。",
      "换 4 档揉至扩展阶段。",
      "加入软化的黄油，1 档揉至黄油被面团吸收。",
      "换 4 档揉出薄膜。",
      "发酵至两倍大。",
      "分成 9 份面团，松弛 15 分钟。",
      "面团压扁，拍掉边缘气泡后滚圆。",
      "每个面团垫一张烘焙纸，发酵至两倍大。",
      "油加热至 170°C，连着油纸将面团下锅炸。",
      "约 10 秒后取走油纸，每面炸约 2 分钟。",
      "冷却后从侧面插入筷子，稍微转动形成空洞。",
      "面包表面滚一层细砂糖。",
      "卡仕达酱搅打顺滑后装入裱花袋，挤入甜甜圈中。"
    ]
  },

  "sausage-buns": {
    title: "肠仔包",
    name: "Sausage Buns",
    image: "../images/sausage-buns.jpeg",
    imagePosition: "center center",
    imageZoom: 1,
    intro: "使用波兰种制作的松软肠仔包",
    ingredients: [
      { type: "heading", text: "波兰种" },
      { name: "肠仔包波兰种高筋面粉", displayName: "高筋面粉", amount: 50, unit: "g" },
      { name: "肠仔包波兰种水", displayName: "水", amount: 50, unit: "g" },
      { name: "肠仔包波兰种干酵母", displayName: "干酵母", amount: 0.7, unit: "g" },
      { name: "肠仔包波兰种糖", displayName: "糖", amount: 7, unit: "g" },

      { type: "heading", text: "主面团" },
      { name: "肠仔包高筋面粉", displayName: "高筋面粉", amount: 200, unit: "g" },
      { name: "肠仔包牛奶", displayName: "牛奶", amount: 80, unit: "g" },
      { name: "肠仔包奶粉", displayName: "奶粉", amount: 10, unit: "g" },
      { name: "肠仔包盐", displayName: "盐", amount: 3, unit: "g" },
      { name: "肠仔包糖", displayName: "糖", amount: 30, unit: "g" },
      { name: "肠仔包干酵母", displayName: "干酵母", amount: 2, unit: "g" },
      { name: "肠仔包全蛋液", displayName: "全蛋液", amount: 25, unit: "g" },
      { name: "肠仔包黄油", displayName: "黄油", amount: 17, unit: "g" },
      { name: "热狗肠", amount: 3, unit: "pc" },
      { name: "肠仔包芝麻", displayName: "芝麻", amount: 0, unit: "适量" }
    ],
    steps: [
      "将 {肠仔包波兰种高筋面粉} 高筋面粉、{肠仔包波兰种水} 水、{肠仔包波兰种干酵母} 干酵母和 {肠仔包波兰种糖} 糖混合均匀。",
      "室温或冷藏发酵至表面有许多气泡，里面呈蜂窝状。",
      "波兰种与除 {肠仔包黄油} 黄油外的所有主面团材料混合，1 档揉成团。",
      "换 4 档揉至扩展阶段。",
      "加入软化的黄油，1 档揉至黄油被面团吸收。",
      "换 4 档揉出手套膜。",
      "在温暖处发酵至两倍大。",
      "发酵完成后分成 9 份小面团，松弛 15 分钟。",
      "【花形造型】",
      "将面团擀成三角形，从右往左卷起并捏紧收口。",
      "所有面团卷好后，取一份擀成长倒三角。",
      "放上一段 {热狗肠} 热狗肠，用面团卷起。",
      "放在温暖处发酵至约两倍大。",
      "烤箱预热至 180°C。",
      "表面刷全蛋液并撒上芝麻。",
      "180°C 烤约 18 分钟。",
      "【另一种造型】",
      "将面团擀成长方形，从上往下卷起并搓长。",
      "把一端擀薄，包住另一端，做成圆环。",
      "中间放入一根热狗肠。",
      "发酵至两倍大，表面刷蛋液，挤上番茄酱和沙拉酱。",
      "撒上欧芹碎，180°C 烤约 15 分钟。"
    ]
  },

  "butter-rolls": {
    title: "黄油餐包",
    name: "Butter Dinner Rolls",
    image: "../images/butter-rolls.jpeg",
    imagePosition: "center center",
    imageZoom: 1,
    intro: "加入牛奶与淡奶油制作的迷你黄油餐包，组织柔软细腻，奶香浓郁。",
    ingredients: [
      { type: "heading", text: "波兰种" },
      { name: "黄油餐包波兰种高筋面粉", displayName: "高筋面粉", amount: 50, unit: "g" },
      { name: "黄油餐包波兰种水", displayName: "水", amount: 50, unit: "g" },
      { name: "黄油餐包波兰种干酵母", displayName: "干酵母", amount: 0.7, unit: "g" },
      { name: "黄油餐包波兰种糖", displayName: "糖", amount: 7, unit: "g" },

      { type: "heading", text: "主面团" },
      { name: "黄油餐包高筋面粉", displayName: "高筋面粉", amount: 200, unit: "g" },
      { name: "黄油餐包牛奶", displayName: "牛奶", amount: 63, unit: "g" },
      { name: "黄油餐包淡奶油", displayName: "淡奶油", amount: 20, unit: "g" },
      { name: "黄油餐包奶粉", displayName: "奶粉", amount: 10, unit: "g" },
      { name: "黄油餐包盐", displayName: "盐", amount: 3, unit: "g" },
      { name: "黄油餐包糖", displayName: "糖", amount: 30, unit: "g" },
      { name: "黄油餐包干酵母", displayName: "干酵母", amount: 2, unit: "g" },
      { name: "黄油餐包全蛋液", displayName: "全蛋液", amount: 25, unit: "g" },
      { name: "黄油餐包黄油", displayName: "黄油", amount: 17, unit: "g" },
      { name: "黄油餐包芝麻", displayName: "芝麻", amount: 0, unit: "适量" }
    ],
    steps: [
      "将 {黄油餐包波兰种高筋面粉} 高筋面粉、{黄油餐包波兰种水} 水、{黄油餐包波兰种干酵母} 干酵母和 {黄油餐包波兰种糖} 糖混合均匀。",
      "室温或冷藏发酵至表面有许多气泡，里面呈蜂窝状。",
      "波兰种与除 {黄油餐包黄油} 黄油外的所有主面团材料混合，1 档揉成团。",
      "换 4 档揉至扩展阶段。",
      "加入软化的黄油，1 档揉至黄油被面团吸收。",
      "换 4 档揉出手套膜。",
      "在温暖处发酵至两倍大。",
      "发酵完成后分成 16 份小面团，松弛 15 分钟。",
      "面团压扁，拍掉边缘气泡后滚圆。",
      "放入模具中，在温暖处发酵至两倍大。",
      "烤箱预热至 180°C。",
      "表面刷蛋液，中间撒上芝麻。",
      "180°C 烤约 16 分钟。"
    ]
  },

  "pork-floss-buns": {
    title: "肉松包",
    name: "Pork Floss Buns",
    image: "../images/pork-floss-buns.jpeg",
    imagePosition: "center center",
    imageZoom: 1,
    intro: "柔软的波兰种面包包入肉松和沙拉酱",
    ingredients: [
      { type: "heading", text: "波兰种" },
      { name: "肉松包波兰种高筋面粉", displayName: "高筋面粉", amount: 50, unit: "g" },
      { name: "肉松包波兰种水", displayName: "水", amount: 50, unit: "g" },
      { name: "肉松包波兰种干酵母", displayName: "干酵母", amount: 0.7, unit: "g" },
      { name: "肉松包波兰种糖", displayName: "糖", amount: 7, unit: "g" },

      { type: "heading", text: "主面团" },
      { name: "肉松包高筋面粉", displayName: "高筋面粉", amount: 200, unit: "g" },
      { name: "肉松包牛奶", displayName: "牛奶", amount: 80, unit: "g" },
      { name: "肉松包奶粉", displayName: "奶粉", amount: 10, unit: "g" },
      { name: "肉松包盐", displayName: "盐", amount: 3, unit: "g" },
      { name: "肉松包糖", displayName: "糖", amount: 30, unit: "g" },
      { name: "肉松包干酵母", displayName: "干酵母", amount: 2, unit: "g" },
      { name: "肉松包全蛋液", displayName: "全蛋液", amount: 25, unit: "g" },
      { name: "肉松包黄油", displayName: "黄油", amount: 17, unit: "g" },
      { name: "肉松", amount: 0, unit: "适量" },
      { name: "沙拉酱", amount: 0, unit: "适量" }
    ],
    steps: [
      "将 {肉松包波兰种高筋面粉} 高筋面粉、{肉松包波兰种水} 水、{肉松包波兰种干酵母} 干酵母和 {肉松包波兰种糖} 糖混合均匀。",
      "室温或冷藏发酵至表面有许多气泡，里面呈蜂窝状。",
      "波兰种与除 {肉松包黄油} 黄油外的所有主面团材料混合，2 档揉成团。",
      "换 4 档揉至扩展阶段。",
      "加入软化的黄油，1 档揉至黄油被面团吸收。",
      "换 4 档揉出手套膜。",
      "在温暖处发酵至两倍大。",
      "发酵完成后分成 9 份面团，每份约 50g，松弛 15 分钟。",
      "面团擀至手掌大小，拍掉边缘气泡。",
      "挤上沙拉酱，放上肉松，上下捏合，像包饺子一样收口。",
      "收口朝下，双手在两端轻轻将面团来回搓几下。",
      "放在温暖处发酵至两倍大。",
      "烤箱预热至 180°C。",
      "表面刷蛋液，中间撒上熟芝麻。",
      "180°C 烤约 14 分钟。",
      "波兰种发酵需观察状态；室温发酵约 3 小时，或室温发酵 1 小时后冷藏隔夜。"
    ]
  },

  "mocha-buns": {
    title: "摩卡面包",
    name: "Mocha Chocolate Buns",
    image: "../images/mocha-buns.jpeg",
    imagePosition: "center center",
    imageZoom: 1,
    intro: "咖啡香面团加入巧克力豆",
    ingredients: [
      { type: "heading", text: "波兰种" },
      { name: "摩卡面包波兰种高筋面粉", displayName: "高筋面粉", amount: 50, unit: "g" },
      { name: "摩卡面包波兰种水", displayName: "水", amount: 50, unit: "g" },
      { name: "摩卡面包波兰种干酵母", displayName: "干酵母", amount: 0.7, unit: "g" },
      { name: "摩卡面包波兰种糖", displayName: "糖", amount: 7, unit: "g" },

      { type: "heading", text: "主面团" },
      { name: "摩卡面包高筋面粉", displayName: "高筋面粉", amount: 200, unit: "g" },
      { name: "摩卡面包牛奶", displayName: "牛奶", amount: 80, unit: "g" },
      { name: "摩卡面包奶粉", displayName: "奶粉", amount: 10, unit: "g" },
      { name: "摩卡面包盐", displayName: "盐", amount: 3, unit: "g" },
      { name: "摩卡面包糖", displayName: "糖", amount: 30, unit: "g" },
      { name: "摩卡面包干酵母", displayName: "干酵母", amount: 2, unit: "g" },
      { name: "摩卡面包全蛋液", displayName: "全蛋液", amount: 25, unit: "g" },
      { name: "速溶咖啡粉", amount: 5, unit: "g" },
      { name: "摩卡面包黄油", displayName: "黄油", amount: 17, unit: "g" },
      { name: "巧克力豆", amount: 30, unit: "g" }
    ],
    steps: [
      "将 {摩卡面包波兰种高筋面粉} 高筋面粉、{摩卡面包波兰种水} 水、{摩卡面包波兰种干酵母} 干酵母和 {摩卡面包波兰种糖} 糖混合均匀。",
      "室温或冷藏发酵至表面有许多气泡，里面呈蜂窝状。",
      "波兰种与除 {摩卡面包黄油} 黄油和 {巧克力豆} 巧克力豆外的所有主面团材料混合，2 档揉成团。",
      "换 4 档揉至扩展阶段。",
      "加入软化的黄油，1 档揉至黄油被面团吸收。",
      "换 4 档揉出手套膜。",
      "用 1 档混入 {巧克力豆} 巧克力豆。",
      "在温暖处发酵至两倍大。",
      "发酵完成后分成 9 份面团，滚圆并松弛 15 分钟。",
      "面团拍扁，拍掉边缘气泡后滚圆。",
      "放入模具中，在温暖处发酵至两倍大。",
      "烤箱预热至 180°C。",
      "发酵好的面团表面刷蛋液并撒上白芝麻。",
      "180°C 烤约 15 分钟。",
      "波兰种发酵需观察状态；室温发酵约 4 小时，或室温发酵 1 小时后冷藏隔夜。"
    ]
  },

  "spinach-rolls": {
    title: "菠菜培根芝士面包",
    name: "Spinach Bacon Cheese Rolls",
    image: "../images/spinach-rolls.jpeg",
    imagePosition: "center center",
    imageZoom: 1,
    intro: "融合菠菜、培根和芝士的营养丰富面包",
    ingredients: [
      { type: "heading", text: "波兰种" },
      { name: "菠菜培根芝士波兰种高筋面粉", displayName: "高筋面粉", amount: 50, unit: "g" },
      { name: "菠菜培根芝士波兰种水", displayName: "水", amount: 50, unit: "g" },
      { name: "菠菜培根芝士波兰种干酵母", displayName: "干酵母", amount: 7, unit: "g" },
      { name: "菠菜培根芝士波兰种糖", displayName: "糖", amount: 7, unit: "g" },

      { type: "heading", text: "主面团" },
      { name: "菠菜培根芝士高筋面粉", displayName: "高筋面粉", amount: 200, unit: "g" },
      { name: "菠菜培根芝士牛奶", displayName: "牛奶", amount: 80, unit: "g" },
      { name: "菠菜培根芝士奶粉", displayName: "奶粉", amount: 10, unit: "g" },
      { name: "菠菜培根芝士盐", displayName: "盐", amount: 3, unit: "g" },
      { name: "菠菜培根芝士糖", displayName: "糖", amount: 25, unit: "g" },
      { name: "菠菜培根芝士干酵母", displayName: "干酵母", amount: 2, unit: "g" },
      { name: "菠菜培根芝士全蛋液", displayName: "全蛋液", amount: 25, unit: "g" },
      { name: "菠菜培根芝士黄油", displayName: "黄油", amount: 17, unit: "g" },
      { name: "菠菜", amount: 80, unit: "g" },
      { name: "培根", amount: 70, unit: "g" },
      { name: "马苏里拉芝士", amount: 80, unit: "pc" }
    ],
    steps: [
      "将 {菠菜培根芝士波兰种高筋面粉} 高筋面粉、{菠菜培根芝士波兰种水} 水、{菠菜培根芝士波兰种干酵母} 干酵母和 {菠菜培根芝士波兰种糖} 糖混合均匀。",
      "室温或冷藏发酵至表面有许多气泡，里面呈蜂窝状。",
      "菠菜蒸熟、培根炒至半熟并切碎。",
      "波兰种与除 {菠菜培根芝士黄油} 黄油外的所有主面团材料混合，1 档揉成团。",
      "换 4 档揉至扩展阶段。",
      "加入软化的黄油，1 档揉至黄油被面团吸收。",
      "换 4 档揉出手套膜。",
      "在温暖处发酵至两倍大。",
      "发酵完成后分成 9 份面团，每份约 50g，松弛 15 分钟。",
      "面团压扁，拍掉边缘气泡。",
      "放入菠菜、培根和芝士，卷起并捏紧收口。",
      "收口朝下放入模具，在温暖处发酵至两倍大。",
      "烤箱预热至 180°C。",
      "表面刷蛋液，中间撒上芝麻。",
      "180°C 烤约 18 分钟。"
    ]
  },

  "matcha-taro-buns": {
    title: "抹茶芋泥包",
    name: "Matcha Taro Buns",
    image: "../images/matcha-taro-buns.jpeg",
    imagePosition: "center center",
    imageZoom: 1,
    intro: "抹茶香面团搭配绵密芋泥馅",
    ingredients: [
      { type: "heading", text: "波兰种" },
      { name: "抹茶芋泥波兰种高筋面粉", displayName: "高筋面粉", amount: 50, unit: "g" },
      { name: "抹茶芋泥波兰种水", displayName: "水", amount: 50, unit: "g" },
      { name: "抹茶芋泥波兰种干酵母", displayName: "干酵母", amount: 0.7, unit: "g" },
      { name: "抹茶芋泥波兰种糖", displayName: "糖", amount: 7, unit: "g" },

      { type: "heading", text: "主面团" },
      { name: "抹茶芋泥高筋面粉", displayName: "高筋面粉", amount: 200, unit: "g" },
      { name: "抹茶芋泥牛奶", displayName: "牛奶", amount: 80, unit: "g" },
      { name: "抹茶粉", displayName: "抹茶粉", amount: 4, unit: "g" },
      { name: "抹茶芋泥奶粉", displayName: "奶粉", amount: 10, unit: "g" },
      { name: "抹茶芋泥盐", displayName: "盐", amount: 3, unit: "g" },
      { name: "抹茶芋泥糖", displayName: "糖", amount: 30, unit: "g" },
      { name: "抹茶芋泥干酵母", displayName: "干酵母", amount: 2, unit: "g" },
      { name: "抹茶芋泥全蛋液", displayName: "全蛋液", amount: 25, unit: "g" },
      { name: "抹茶芋泥黄油", displayName: "黄油", amount: 17, unit: "g" },
      { name: "芋头", displayName: "芋头", amount: 250, unit: "g" },
      { name: "炼乳", displayName: "炼乳", amount: 15, unit: "g" },
      { name: "无盐黄油", displayName: "无盐黄油", amount: 15, unit: "g" }
    ],
    steps: [
      "将 {抹茶芋泥波兰种高筋面粉} 高筋面粉、{抹茶芋泥波兰种水} 水、{抹茶芋泥波兰种干酵母} 干酵母和 {抹茶芋泥波兰种糖} 糖混合均匀。",
      "室温或冷藏发酵至表面有许多气泡，里面呈蜂窝状。",
      "【芋泥馅】芋头蒸熟压成泥，加入 {炼乳} 炼乳和 {无盐黄油} 黄油混合均匀。",
      "冷藏备用。",
      "波兰种与除 {抹茶芋泥黄油} 黄油外的所有主面团材料混合，1 档揉成团。",
      "换 4 档揉至扩展阶段。",
      "加入软化的黄油，1 档揉至黄油被面团吸收。",
      "换 4 档揉出手套膜。",
      "在温暖处发酵至两倍大。",
      "发酵完成后分成 9 份面团，松弛 15 分钟。",
      "面团压扁，包入约 30g 芋泥馅。",
      "收口朝下，滚圆。",
      "放在温暖处发酵至两倍大。",
      "烤箱预热至 180°C。",
      "刷上蛋液，撒上芝麻。",
      "180°C 烤约 18 分钟。"
    ]
  },

  "matcha-milk-buns": {
    title: "抹茶奶酥包",
    name: "Matcha Milk Buns",
    image: "../images/matcha-milk-buns.jpeg",
    imagePosition: "center center",
    imageZoom: 1,
    intro: "面团配上抹茶奶酥",
    ingredients: [
      { type: "heading", text: "波兰种" },
      { name: "抹茶奶酥波兰种高筋面粉", displayName: "高筋面粉", amount: 50, unit: "g" },
      { name: "抹茶奶酥波兰种水", displayName: "水", amount: 50, unit: "g" },
      { name: "抹茶奶酥波兰种干酵母", displayName: "干酵母", amount: 0.7, unit: "g" },
      { name: "抹茶奶酥波兰种糖", displayName: "糖", amount: 7, unit: "g" },

      { type: "heading", text: "主面团" },
      { name: "抹茶奶酥高筋面粉", displayName: "高筋面粉", amount: 200, unit: "g" },
      { name: "抹茶奶酥牛奶", displayName: "牛奶", amount: 80, unit: "g" },
      { name: "抹茶奶粉", displayName: "抹茶粉", amount: 4, unit: "g" },
      { name: "抹茶奶酥奶粉", displayName: "奶粉", amount: 10, unit: "g" },
      { name: "抹茶奶酥盐", displayName: "盐", amount: 3, unit: "g" },
      { name: "抹茶奶酥糖", displayName: "糖", amount: 30, unit: "g" },
      { name: "抹茶奶酥干酵母", displayName: "干酵母", amount: 2, unit: "g" },
      { name: "抹茶奶酥全蛋液", displayName: "全蛋液", amount: 25, unit: "g" },
      { name: "抹茶奶酥黄油", displayName: "黄油", amount: 17, unit: "g" },
      { name: "抹茶奶酥粉", displayName: "抹茶奶酥粉", amount: 25, unit: "g" },
      { name: "无盐黄油", displayName: "无盐黄油", amount: 25, unit: "g" },
      { name: "糖粉", displayName: "糖粉", amount: 10, unit: "g" },
      { name: "奶粉", displayName: "奶粉", amount: 35, unit: "g" },
      { name: "抹茶粉", displayName: "抹茶粉", amount: 3, unit: "g" }
    ],
    steps: [
      "将 {抹茶奶酥波兰种高筋面粉} 高筋面粉、{抹茶奶酥波兰种水} 水、{抹茶奶酥波兰种干酵母} 干酵母和 {抹茶奶酥波兰种糖} 糖混合均匀。",
      "室温或冷藏发酵至表面有许多气泡，里面呈蜂窝状。",
      "【奶酥粒】软化黄油与糖粉和奶粉混合均匀，制成粗粉状。",
      "冷藏备用。",
      "波兰种与除 {抹茶奶酥黄油} 黄油外的所有主面团材料混合，1 档揉成团。",
      "换 4 档揉至扩展阶段。",
      "加入软化的黄油，1 档揉至黄油被面团吸收。",
      "换 4 档揉出手套膜。",
      "在温暖处发酵至两倍大。",
      "发酵完成后分成 9 份面团，滚圆并松弛 15 分钟。",
      "面团压扁，拍掉边缘气泡后滚圆。",
      "放在温暖处发酵至两倍大。",
      "烤箱预热至 180°C。",
      "刷上蛋液，撒上奶酥粒。",
      "180°C 烤约 18 分钟。"
    ]
  },

  "pumpkin-taro-buns": {
    title: "南瓜芋泥包",
    name: "Pumpkin Taro Buns",
    image: "../images/pumpkin-taro-buns.jpeg",
    imagePosition: "center center",
    imageZoom: 1,
    intro: "南瓜色的面团内馅是绵密芋泥",
    ingredients: [
      { type: "heading", text: "波兰种" },
      { name: "南瓜芋泥波兰种高筋面粉", displayName: "高筋面粉", amount: 50, unit: "g" },
      { name: "南瓜芋泥波兰种水", displayName: "水", amount: 50, unit: "g" },
      { name: "南瓜芋泥波兰种干酵母", displayName: "干酵母", amount: 7, unit: "g" },
      { name: "南瓜芋泥波兰种糖", displayName: "糖", amount: 7, unit: "g" },

      { type: "heading", text: "主面团" },
      { name: "南瓜芋泥高筋面粉", displayName: "高筋面粉", amount: 200, unit: "g" },
      { name: "南瓜芋泥水", displayName: "水", amount: 10, unit: "g" },
      { name: "南瓜泥", displayName: "南瓜泥", amount: 100, unit: "g" },
      { name: "南瓜芋泥奶粉", displayName: "奶粉", amount: 10, unit: "g" },
      { name: "南瓜芋泥盐", displayName: "盐", amount: 3, unit: "g" },
      { name: "南瓜芋泥糖", displayName: "糖", amount: 30, unit: "g" },
      { name: "南瓜芋泥干酵母", displayName: "干酵母", amount: 2, unit: "g" },
      { name: "南瓜芋泥全蛋液", displayName: "全蛋液", amount: 25, unit: "g" },
      { name: "南瓜芋泥黄油", displayName: "黄油", amount: 17, unit: "g" },
      { name: "芋头", displayName: "芋头", amount: 250, unit: "g" },
      { name: "紫薯粉", displayName: "紫薯粉", amount: 1, unit: "tsp" },
      { name: "炼乳", displayName: "炼乳", amount: 20, unit: "g" },
      { name: "无盐黄油", displayName: "无盐黄油", amount: 15, unit: "g" },
      { name: "糖", displayName: "糖", amount: 20, unit: "g" },
      { name: "奶粉", displayName: "奶粉", amount: 10, unit: "g" }
    ],
    steps: [
      "将 {南瓜芋泥波兰种高筋面粉} 高筋面粉、{南瓜芋泥波兰种水} 水、{南瓜芋泥波兰种干酵母} 干酵母和 {南瓜芋泥波兰种糖} 糖混合均匀。",
      "室温或冷藏发酵至表面有许多气泡，里面呈蜂窝状。",
      "【芋泥馅】芋头蒸熟压成泥，加入 {炼乳} 炼乳和 {无盐黄油} 黄油混合均匀。",
      "冷藏备用。",
      "波兰种与除 {南瓜芋泥黄油} 黄油外的所有主面团材料混合，1 档揉成团。",
      "换 4 档揉至扩展阶段。",
      "加入软化的黄油，1 档揉至黄油被面团吸收。",
      "换 4 档揉出手套膜。",
      "在温暖处发酵至两倍大。",
      "发酵完成后分成 9 份面团，松弛 15 分钟。",
      "面团压扁，包入约 30g 芋泥馅，收口朝下放入模具。",
      "在温暖处发酵至两倍大。",
      "烤箱预热至 180°C。",
      "刷上蛋液，撒上芝麻。",
      "180°C 烤约 18 分钟。"
    ]
  },

  "pumpkin-buns": {
    title: "南瓜包",
    name: "Pumpkin Buns",
    image: "../images/pumpkin-buns.jpeg",
    imagePosition: "center center",
    imageZoom: 1,
    intro: "南瓜面包包入南瓜馅，并用棉绳塑造成南瓜外形。",
    ingredients: [
      { type: "heading", text: "波兰种" },
      { name: "南瓜包波兰种高筋面粉", displayName: "高筋面粉", amount: 50, unit: "g" },
      { name: "南瓜包波兰种水", displayName: "水", amount: 50, unit: "g" },
      { name: "南瓜包波兰种干酵母", displayName: "干酵母", amount: 0.7, unit: "g" },
      { name: "南瓜包波兰种糖", displayName: "糖", amount: 7, unit: "g" },

      { type: "heading", text: "主面团" },
      { name: "南瓜包高筋面粉", displayName: "高筋面粉", amount: 200, unit: "g" },
      { name: "南瓜包牛奶", displayName: "牛奶", amount: 5, unit: "g" },
      { name: "南瓜泥", amount: 100, unit: "g" },
      { name: "南瓜包奶粉", displayName: "奶粉", amount: 10, unit: "g" },
      { name: "南瓜包盐", displayName: "盐", amount: 3, unit: "g" },
      { name: "南瓜包糖", displayName: "糖", amount: 30, unit: "g" },
      { name: "南瓜包干酵母", displayName: "干酵母", amount: 2, unit: "g" },
      { name: "南瓜包全蛋液", displayName: "全蛋液", amount: 25, unit: "g" },
      { name: "南瓜包黄油", displayName: "黄油", amount: 25, unit: "g" },

      { type: "heading", text: "南瓜馅" },
      { name: "馅料南瓜", displayName: "南瓜", amount: 250, unit: "g" },
      { name: "馅料奶粉", displayName: "奶粉", amount: 10, unit: "tsp" },
      { name: "馅料玉米淀粉", displayName: "玉米淀粉", amount: 10, unit: "g" },
      { name: "馅料细砂糖", displayName: "细砂糖", amount: 25, unit: "g" },
      { name: "馅料黄油", displayName: "黄油", amount: 10, unit: "g" }
    ],
    steps: [
      "【南瓜馅】",
      "{馅料南瓜} 南瓜蒸熟后用料理机打成泥。",
      "取一部分南瓜泥揉入面团，先冷藏降温。",
      "剩下的南瓜泥与 {馅料奶粉} 奶粉、{馅料玉米淀粉} 玉米淀粉、{馅料细砂糖} 细砂糖和 {馅料黄油} 黄油混合。",
      "小火炒制成团，冷藏后会变得更浓稠。",

      "【面团】",
      "将所有波兰种材料混合均匀。",
      "室温或冷藏发酵至表面有许多气泡，里面呈蜂窝状。",
      "波兰种与除 {南瓜包黄油} 黄油外的主面团材料混合，2 档揉成团。",
      "换 4 档揉至扩展阶段。",
      "加入软化的黄油，1 档揉至黄油被面团吸收。",
      "换 4 档揉出手套膜。",
      "在温暖处发酵至两倍大。",
      "面团分成 9 份，松弛 15 分钟。",
      "小面团擀开，拍掉边缘气泡。",
      "包入约 20-25g 南瓜馅，收口朝下。",
      "用 4 根浸过油的棉绳将面团松松地绑起来。",
      "发酵至两倍大。",
      "烤箱预热至 180°C，表面刷全蛋液。",
      "180°C 中层烤约 16 分钟。",
      "冷却后拆掉棉绳，中间插入南瓜籽装饰。"
    ]
  },

  "taro-custard-buns": {
    title: "芋泥卡仕达包",
    name: "Taro Custard Buns",
    image: "../images/taro-custard-buns.jpeg",
    imagePosition: "center center",
    imageZoom: 1,
    intro: "面团包入芋泥和香草卡仕达",
    ingredients: [
      { type: "heading", text: "波兰种" },
      { name: "芋泥卡仕达波兰种高筋面粉", displayName: "高筋面粉", amount: 50, unit: "g" },
      { name: "芋泥卡仕达波兰种水", displayName: "水", amount: 50, unit: "g" },
      { name: "芋泥卡仕达波兰种干酵母", displayName: "干酵母", amount: 0.7, unit: "g" },
      { name: "芋泥卡仕达波兰种糖", displayName: "糖", amount: 7, unit: "g" },

      { type: "heading", text: "主面团" },
      { name: "芋泥卡仕达高筋面粉", displayName: "高筋面粉", amount: 200, unit: "g" },
      { name: "芋泥包主面团牛奶", displayName: "牛奶", amount: 80, unit: "g" },
      { name: "抹茶粉", amount: 4, unit: "g" },
      { name: "芋泥卡仕达奶粉", displayName: "奶粉", amount: 10, unit: "g" },
      { name: "芋泥卡仕达盐", displayName: "盐", amount: 3, unit: "g" },
      { name: "芋泥包主面团糖", displayName: "糖", amount: 30, unit: "g" },
      { name: "芋泥卡仕达干酵母", displayName: "干酵母", amount: 2, unit: "g" },
      { name: "芋泥卡仕达全蛋液", displayName: "全蛋液", amount: 25, unit: "g" },
      { name: "芋泥卡仕达黄油", displayName: "黄油", amount: 17, unit: "g" },

      { type: "heading", text: "芋泥馅" },
      { name: "芋头", amount: 125, unit: "g" },
      { name: "芋泥牛奶", displayName: "牛奶", amount: 20, unit: "g" },
      { name: "炼乳", amount: 12, unit: "g" },
      { name: "椰子油", amount: 7, unit: "g" },
      { name: "芋泥奶粉", displayName: "奶粉", amount: 5, unit: "g" },
      { name: "紫薯粉", amount: 0.25, unit: "g" },
      { name: "芋泥糖", displayName: "糖", amount: 12, unit: "g" },

      { type: "heading", text: "卡仕达" },
      { name: "芋泥卡仕达蛋黄", displayName: "蛋黄", amount: 1, unit: "pc" },
      { name: "芋泥卡仕达酱糖", displayName: "糖", amount: 15, unit: "g" },
      { name: "芋泥卡仕达玉米淀粉", displayName: "玉米淀粉", amount: 8, unit: "g" },
      { name: "芋泥卡仕达牛奶", displayName: "牛奶", amount: 100, unit: "g" },
      { name: "芋泥卡仕达香草精", displayName: "香草精", amount: 0, unit: "适量" }
    ],
    steps: [
      "【芋泥馅】",
      "{芋头} 芋头切块蒸熟。",
      "趁热加入 {芋泥牛奶} 牛奶、{炼乳} 炼乳、{椰子油} 椰子油、{芋泥奶粉} 奶粉、{紫薯粉} 紫薯粉和 {芋泥糖} 糖。",
      "碾压成泥或用料理机打至细腻，冷藏备用。",

      "【卡仕达】",
      "{芋泥卡仕达蛋黄} 蛋黄和 {芋泥卡仕达酱糖} 糖搅拌至发白。",
      "混入 {芋泥卡仕达玉米淀粉} 玉米淀粉和香草精。",
      "{芋泥卡仕达牛奶} 牛奶加热至冒小泡，少量多次倒入蛋黄糊。",
      "混合均匀后倒回锅中，小火加热并不断搅拌至浓稠。",
      "冒泡后关火，冷却备用。",

      "【面团与组装】",
      "将所有波兰种材料混合均匀并发酵至蜂窝状。",
      "波兰种与除 {芋泥卡仕达黄油} 黄油外的主面团材料混合，2 档揉成团。",
      "换 4 档揉至扩展阶段。",
      "加入软化的黄油，1 档揉至吸收，再换 4 档揉出手套膜。",
      "在温暖处发酵至两倍大。",
      "面团分成 9 份，每份约 50g，松弛 15 分钟。",
      "小面团擀开，拍掉边缘气泡。",
      "翻面后先包入约 20g 芋泥，再放入约 10g 卡仕达。",
      "收口捏紧并朝下，稍微按扁。",
      "在温暖处发酵至约两倍大。",
      "烤箱预热至 180°C，表面刷蛋液并撒黑芝麻。",
      "180°C 中层烤约 17 分钟。"
    ]
  },

  "red-bean-custard-buns": {
    title: "红豆卡仕达包",
    name: "Red Bean Custard Buns",
    image: "../images/red-bean-custard-buns.jpeg",
    imagePosition: "center center",
    imageZoom: 1,
    intro: "面团包入自制红豆馅和香草卡仕达",
    ingredients: [
      { type: "heading", text: "波兰种" },
      { name: "红豆卡仕达波兰种高筋面粉", displayName: "高筋面粉", amount: 50, unit: "g" },
      { name: "红豆卡仕达波兰种水", displayName: "水", amount: 50, unit: "g" },
      { name: "红豆卡仕达波兰种干酵母", displayName: "干酵母", amount: 0.7, unit: "g" },
      { name: "红豆卡仕达波兰种糖", displayName: "糖", amount: 7, unit: "g" },

      { type: "heading", text: "主面团" },
      { name: "红豆卡仕达高筋面粉", displayName: "高筋面粉", amount: 200, unit: "g" },
      { name: "红豆包主面团牛奶", displayName: "牛奶", amount: 80, unit: "g" },
      { name: "红豆卡仕达抹茶粉", displayName: "抹茶粉", amount: 4, unit: "g" },
      { name: "红豆卡仕达奶粉", displayName: "奶粉", amount: 10, unit: "g" },
      { name: "红豆卡仕达盐", displayName: "盐", amount: 3, unit: "g" },
      { name: "红豆卡仕达糖", displayName: "糖", amount: 25, unit: "g" },
      { name: "红豆卡仕达干酵母", displayName: "干酵母", amount: 2, unit: "g" },
      { name: "红豆卡仕达全蛋液", displayName: "全蛋液", amount: 25, unit: "g" },
      { name: "红豆卡仕达黄油", displayName: "黄油", amount: 17, unit: "g" },

      { type: "heading", text: "红豆馅" },
      { name: "红豆", amount: 100, unit: "g" },
      { name: "红糖", amount: 45, unit: "g" },
      { name: "红豆馅细砂糖", displayName: "细砂糖", amount: 45, unit: "g" },
      { name: "煮红豆水", displayName: "水", amount: 300, unit: "g" },
      { name: "红豆馅黄油", displayName: "黄油", amount: 10, unit: "g" },
      { name: "红豆馅盐", displayName: "盐", amount: 1, unit: "g" },

      { type: "heading", text: "卡仕达" },
      { name: "红豆卡仕达蛋黄", displayName: "蛋黄", amount: 1, unit: "pc" },
      { name: "红豆卡仕达酱糖", displayName: "糖", amount: 15, unit: "g" },
      { name: "红豆卡仕达玉米淀粉", displayName: "玉米淀粉", amount: 8, unit: "g" },
      { name: "红豆卡仕达牛奶", displayName: "牛奶", amount: 100, unit: "g" },
      { name: "红豆卡仕达香草精", displayName: "香草精", amount: 0, unit: "适量" }
    ],
    steps: [
      "【红豆馅】",
      "{红豆} 红豆隔夜浸泡后清洗干净。",
      "锅中倒入红豆和 {煮红豆水} 水，煮开后转小火煮 5 分钟。",
      "倒掉水以去除涩味。",
      "重新倒入约 400ml 冷水，小火煮约 35 分钟。",
      "中途检查水量，避免烧干。",
      "红豆煮软后加入 {红豆馅黄油} 黄油、{红糖} 红糖、{红豆馅细砂糖} 细砂糖和 {红豆馅盐} 盐，大火收汁。",
      "馅料不要煮得太干，冷却时水分还会继续蒸发。",

      "【卡仕达】",
      "{红豆卡仕达蛋黄} 蛋黄和 {红豆卡仕达酱糖} 糖搅拌至发白。",
      "混入 {红豆卡仕达玉米淀粉} 玉米淀粉和香草精。",
      "{红豆卡仕达牛奶} 牛奶加热至冒小泡，少量多次倒入蛋黄糊。",
      "混合均匀后倒回锅中，小火加热并搅拌至浓稠。",
      "冒泡后关火，冷却备用。",

      "【面团与组装】",
      "将所有波兰种材料混合均匀并发酵至蜂窝状。",
      "波兰种与除 {红豆卡仕达黄油} 黄油外的主面团材料混合，2 档揉成团。",
      "换 4 档揉至扩展阶段。",
      "加入软化的黄油，1 档揉至吸收，再换 4 档揉出手套膜。",
      "在温暖处发酵至两倍大。",
      "面团分成 9 份，每份约 50g，松弛 15 分钟。",
      "小面团擀开，拍掉边缘气泡。",
      "先放入约 20g 红豆馅，再放入约 10g 卡仕达。",
      "收口捏紧并朝下。",
      "发酵至约两倍大。",
      "烤箱预热至 180°C，表面刷蛋液并粘上芝麻。",
      "180°C 中层烤约 16 分钟。"
    ]
  },

  "cranberry-cheese-buns": {
    title: "蔓越莓奶酪包",
    name: "Cranberry Cream Cheese Buns",
    image: "../images/cranberry-cheese-buns.jpeg",
    imagePosition: "center center",
    imageZoom: 1,
    intro: "蔓越莓奶酪馅，并撒上香酥粒烘烤。",
    ingredients: [
      { type: "heading", text: "波兰种" },
      { name: "蔓越莓奶酪波兰种高筋面粉", displayName: "高筋面粉", amount: 50, unit: "g" },
      { name: "蔓越莓奶酪波兰种水", displayName: "水", amount: 50, unit: "g" },
      { name: "蔓越莓奶酪波兰种干酵母", displayName: "干酵母", amount: 0.7, unit: "g" },
      { name: "蔓越莓奶酪波兰种糖", displayName: "糖", amount: 7, unit: "g" },

      { type: "heading", text: "主面团" },
      { name: "蔓越莓奶酪高筋面粉", displayName: "高筋面粉", amount: 200, unit: "g" },
      { name: "蔓越莓奶酪牛奶", displayName: "牛奶", amount: 80, unit: "g" },
      { name: "蔓越莓奶酪奶粉", displayName: "奶粉", amount: 10, unit: "g" },
      { name: "蔓越莓奶酪盐", displayName: "盐", amount: 3, unit: "g" },
      { name: "蔓越莓奶酪糖", displayName: "糖", amount: 25, unit: "g" },
      { name: "蔓越莓奶酪干酵母", displayName: "干酵母", amount: 2, unit: "g" },
      { name: "蔓越莓奶酪全蛋液", displayName: "全蛋液", amount: 25, unit: "g" },
      { name: "蔓越莓奶酪黄油", displayName: "黄油", amount: 17, unit: "g" },

      { type: "heading", text: "奶酪馅" },
      { name: "奶油芝士", amount: 180, unit: "g" },
      { name: "奶酪馅糖粉", displayName: "糖粉", amount: 18, unit: "g" },
      { name: "切碎蔓越莓", displayName: "蔓越莓（切碎）", amount: 25, unit: "g" },

      { type: "heading", text: "酥粒" },
      { name: "酥粒黄油", displayName: "黄油", amount: 15, unit: "g" },
      { name: "酥粒细砂糖", displayName: "细砂糖", amount: 15, unit: "g" },
      { name: "酥粒低筋面粉", displayName: "低筋面粉", amount: 35, unit: "g" }
    ],
    steps: [
      "【提前准备】",
      "面团第一次发酵时，将 {奶油芝士} 奶油芝士软化。",
      "加入 {奶酪馅糖粉} 糖粉和 {切碎蔓越莓} 切碎蔓越莓，混合均匀后冷藏备用。",
      "将 {酥粒黄油} 黄油、{酥粒细砂糖} 细砂糖和 {酥粒低筋面粉} 低筋面粉混合。",
      "搓成细沙状酥粒，冷藏备用。",

      "【面团与组装】",
      "将所有波兰种材料混合均匀并发酵至蜂窝状。",
      "波兰种与除 {蔓越莓奶酪黄油} 黄油外的主面团材料混合，2 档揉成团。",
      "换 4 档揉至扩展阶段。",
      "加入软化的黄油，1 档揉至吸收，再换 4 档揉出手套膜。",
      "在温暖处发酵至两倍大。",
      "面团分成 9 份，每份约 50g，松弛 15 分钟。",
      "小面团擀开，拍掉边缘气泡。",
      "翻面后包入约 25g 奶酪馅。",
      "收口捏紧并朝下放入模具中。",
      "发酵至约两倍大。",
      "烤箱预热至 180°C。",
      "表面刷蛋液并撒上酥粒。",
      "180°C 中下层烤约 18 分钟。",
      "出炉后震两下排出热气。"
    ]
  },

"taro-yogurt-buns": {
    title: "酸奶芋泥包",
    name: "Yogurt Taro Buns",
    image: "../images/taro-yogurt-buns.jpeg",
    imagePosition: "center center",
    imageZoom: 1,
    intro: "波兰种酸奶面包",
    ingredients: [
      { type: "heading", text: "波兰种" },
      { name: "酸奶芋泥波兰种高筋面粉", displayName: "高筋面粉", amount: 50, unit: "g" },
      { name: "酸奶芋泥波兰种水", displayName: "水", amount: 50, unit: "g" },
      { name: "酸奶芋泥波兰种干酵母", displayName: "干酵母", amount: 0.7, unit: "g" },
      { name: "酸奶芋泥波兰种糖", displayName: "糖", amount: 7, unit: "g" },

      { type: "heading", text: "主面团" },
      { name: "酸奶芋泥高筋面粉", displayName: "高筋面粉", amount: 200, unit: "g" },
      { name: "酸奶芋泥牛奶", displayName: "牛奶", amount: 20, unit: "g" },
      { name: "酸奶", amount: 80, unit: "g" },
      { name: "酸奶芋泥奶粉", displayName: "奶粉", amount: 10, unit: "g" },
      { name: "酸奶芋泥盐", displayName: "盐", amount: 3, unit: "g" },
      { name: "酸奶芋泥糖", displayName: "糖", amount: 30, unit: "g" },
      { name: "酸奶芋泥干酵母", displayName: "干酵母", amount: 2, unit: "g" },
      { name: "酸奶芋泥全蛋液", displayName: "全蛋液", amount: 25, unit: "g" },
      { name: "酸奶芋泥黄油", displayName: "黄油", amount: 17, unit: "g" },

      { type: "heading", text: "芋泥馅" },
      { name: "酸奶芋泥芋头", displayName: "芋头", amount: 250, unit: "g" },
      { name: "芋泥馅牛奶", displayName: "牛奶", amount: 30, unit: "g" },
      { name: "炼乳", amount: 15, unit: "g" },
      { name: "芋泥馅无盐黄油", displayName: "无盐黄油", amount: 15, unit: "g" },
      { name: "芋泥馅糖", displayName: "糖", amount: 25, unit: "g" },
      { name: "芋泥馅奶粉", displayName: "奶粉", amount: 10, unit: "g" },
      { name: "紫薯粉", amount: 0.5, unit: "tsp" }
    ],
    steps: [
      "【波兰种】",
      "将所有波兰种材料混合均匀。",
      "室温或冷藏发酵至表面有许多气泡，里面呈蜂窝状。",

      "【主面团】",
      "波兰种与除 {酸奶芋泥黄油} 黄油外的主面团材料混合，2 档揉成团。",
      "换 4 档揉至扩展阶段。",
      "加入软化的黄油，1 档揉至黄油被面团吸收。",
      "换 4 档揉出手套膜。",
      "在温暖处发酵至两倍大。",

      "【芋泥馅】",
      "{酸奶芋泥芋头} 芋头蒸熟。",
      "趁热加入 {芋泥馅牛奶} 牛奶、{炼乳} 炼乳、{芋泥馅无盐黄油} 无盐黄油、{芋泥馅糖} 糖、{芋泥馅奶粉} 奶粉和 {紫薯粉} 紫薯粉。",
      "碾压成泥或用料理机打至细腻，冷藏备用。",

      "【整形与烘烤】",
      "面团发酵完成后分成 9 份，每份约 50g，松弛 15 分钟。",
      "小面团擀开，拍掉边缘气泡。",
      "翻面后擀成牛舌状。",
      "放入约 25g 芋泥馅，将面皮两头捏紧。",
      "收口朝下，双手在两端轻轻搓几下。",
      "放在温暖处发酵至约两倍大。",
      "烤箱预热至 180°C。",
      "表面刷全蛋液并撒上椰蓉。",
      "180°C 中层烤约 17 分钟。"
    ]
  },

  "poolish-pineapple-buns": {
    title: "波兰种菠萝包",
    name: "Poolish Pineapple Buns",
    image: "../images/poolish-pineapple-buns.jpeg",
    imagePosition: "center center",
    imageZoom: 1,
    intro: "外层酥香，内部柔软。",
    ingredients: [
      { type: "heading", text: "波兰种" },
      { name: "菠萝包波兰种高筋面粉", displayName: "高筋面粉", amount: 50, unit: "g" },
      { name: "菠萝包波兰种水", displayName: "水", amount: 50, unit: "g" },
      { name: "菠萝包波兰种干酵母", displayName: "干酵母", amount: 0.7, unit: "g" },
      { name: "菠萝包波兰种糖", displayName: "糖", amount: 7, unit: "g" },

      { type: "heading", text: "主面团" },
      { name: "菠萝包高筋面粉", displayName: "高筋面粉", amount: 200, unit: "g" },
      { name: "菠萝包牛奶", displayName: "牛奶", amount: 80, unit: "g" },
      { name: "菠萝包奶粉", displayName: "奶粉", amount: 10, unit: "g" },
      { name: "菠萝包盐", displayName: "盐", amount: 3, unit: "g" },
      { name: "菠萝包糖", displayName: "糖", amount: 30, unit: "g" },
      { name: "菠萝包干酵母", displayName: "干酵母", amount: 2, unit: "g" },
      { name: "菠萝包全蛋液", displayName: "全蛋液", amount: 25, unit: "g" },
      { name: "菠萝包黄油", displayName: "黄油", amount: 17, unit: "g" },

      { type: "heading", text: "菠萝皮" },
      { name: "菠萝皮低筋面粉", displayName: "低筋面粉", amount: 90, unit: "g" },
      { name: "菠萝皮黄油", displayName: "黄油", amount: 45, unit: "g" },
      { name: "菠萝皮糖粉", displayName: "糖粉", amount: 40, unit: "g" },
      { name: "菠萝皮全蛋液", displayName: "全蛋液", amount: 20, unit: "g" },
      { name: "菠萝皮奶粉", displayName: "奶粉", amount: 9, unit: "g" },
      { name: "菠萝皮苏打粉", displayName: "苏打粉", amount: 0.5, unit: "g" },
      { name: "菠萝皮泡打粉", displayName: "泡打粉", amount: 1, unit: "g" }
    ],
    steps: [
      "【菠萝皮】",
      "{菠萝皮黄油} 黄油软化后加入 {菠萝皮糖粉} 糖粉，搅拌均匀。",
      "分两次加入 {菠萝皮全蛋液} 全蛋液，每次加入后都搅拌均匀。",
      "筛入 {菠萝皮低筋面粉} 低筋面粉、{菠萝皮奶粉} 奶粉、{菠萝皮苏打粉} 苏打粉和 {菠萝皮泡打粉} 泡打粉。",
      "搅拌至无干粉后用保鲜膜包裹。",
      "冷藏松弛至少 1 小时。",

      "【波兰种与主面团】",
      "将所有波兰种材料混合均匀。",
      "室温或冷藏发酵至表面有许多气泡，里面呈蜂窝状。",
      "波兰种与除 {菠萝包黄油} 黄油外的主面团材料混合，2 档揉成团。",
      "换 4 档揉至扩展阶段。",
      "加入软化的黄油，1 档揉至黄油被面团吸收。",
      "换 4 档揉出手套膜。",
      "在温暖处发酵至两倍大。",

      "【整形与烘烤】",
      "面团发酵完成后分成 9 份，每份约 50g，松弛 15 分钟。",
      "同时将菠萝皮分成 9 份，每份约 20g，冷藏备用。",
      "发酵好的面团擀至手掌大小，拍掉边缘气泡后滚圆。",
      "将菠萝皮放在保鲜膜中，压至手掌大小。",
      "把菠萝皮盖在面团上，并用菠萝印压出花纹。",
      "放在温暖处发酵至约两倍大。",
      "烤箱预热至 180°C。",
      "表面刷全蛋液。",
      "180°C 烤约 18 分钟。",
      "喜欢大一点的菠萝包时，可以将面团分成 8 份。",
      "波兰种需按状态判断；可室温发酵约 3 小时，或室温发酵 1 小时后冷藏隔夜。"
    ]
  },

"coconut-buns": {
    title: "椰皇包",
    name: "Coconut Buns",
    image: "../images/coconut-buns.jpeg",
    imagePosition: "center center",
    imageZoom: 1,
    intro: "柔软的波兰种面包挤上香浓椰蓉酱烘烤，表面金黄酥香，椰香浓郁。",
    ingredients: [
      { type: "heading", text: "波兰种" },
      { name: "椰皇包波兰种高筋面粉", displayName: "高筋面粉", amount: 50, unit: "g" },
      { name: "椰皇包波兰种水", displayName: "水", amount: 50, unit: "g" },
      { name: "椰皇包波兰种干酵母", displayName: "干酵母", amount: 0.7, unit: "g" },
      { name: "椰皇包波兰种糖", displayName: "糖", amount: 7, unit: "g" },

      { type: "heading", text: "主面团" },
      { name: "椰皇包高筋面粉", displayName: "高筋面粉", amount: 200, unit: "g" },
      { name: "椰皇包牛奶", displayName: "牛奶", amount: 80, unit: "g" },
      { name: "椰皇包奶粉", displayName: "奶粉", amount: 10, unit: "g" },
      { name: "椰皇包盐", displayName: "盐", amount: 3, unit: "g" },
      { name: "椰皇包糖", displayName: "糖", amount: 30, unit: "g" },
      { name: "椰皇包干酵母", displayName: "干酵母", amount: 2, unit: "g" },
      { name: "椰皇包全蛋液", displayName: "全蛋液", amount: 25, unit: "g" },
      { name: "椰皇包黄油", displayName: "黄油", amount: 17, unit: "g" },

      { type: "heading", text: "椰蓉酱" },
      { name: "椰蓉酱全蛋液", displayName: "全蛋液", amount: 25, unit: "g" },
      { name: "炼乳", amount: 22, unit: "g" },
      { name: "椰蓉酱融化黄油", displayName: "融化黄油", amount: 20, unit: "g" },
      { name: "椰蓉", amount: 17, unit: "g" }
    ],
    steps: [
      "【椰蓉酱】",
      "{椰蓉酱全蛋液} 全蛋液、{炼乳} 炼乳和 {椰蓉酱融化黄油} 融化黄油混合均匀。",
      "倒入 {椰蓉} 椰蓉，搅拌均匀。",
      "装入裱花袋中，冷藏备用。",

      "【面团】",
      "将所有波兰种材料混合均匀。",
      "室温或冷藏发酵至约 3 倍大，表面有许多气泡，里面呈蜂窝状。",
      "波兰种与除 {椰皇包黄油} 黄油外的主面团材料混合，2 档揉成团。",
      "换 4 档揉至扩展阶段。",
      "加入软化的黄油，1 档揉至黄油被面团吸收。",
      "换 4 档揉出手套膜。",
      "在温暖处发酵至两倍大。",
      "发酵完成后分成 9 份面团，每份约 50g，松弛 15 分钟。",
      "将小面团擀长，拍掉边缘气泡。",
      "翻面后将靠近自己的一端擀薄。",
      "从上往下卷起，捏紧收口。",
      "双手轻轻搓动面团，整理形状。",
      "放在温暖处发酵至约两倍大。",
      "烤箱预热至 180°C。",
      "表面刷全蛋液。",
      "用锋利刀片在面团上割一刀。",
      "在割口挤上椰蓉酱。",
      "180°C 中层烤约 18 分钟。",
      "波兰种发酵需观察状态；温暖天气室温约 2 小时，或室温发酵 1 小时后冷藏隔夜。"
    ]
  },

  "coconut-pull-bread": {
    title: "椰蓉包",
    name: "Coconut Pull Bread",
    image: "../images/coconut-pull-buns.jpeg",
    imagePosition: "center center",
    imageZoom: 1,
    intro: "柔软的波兰种面包卷入香甜椰蓉馅，烘烤后形成层层分明的拉丝椰蓉面包。",
    ingredients: [
      { type: "heading", text: "波兰种" },
      { name: "椰蓉包波兰种高筋面粉", displayName: "高筋面粉", amount: 50, unit: "g" },
      { name: "椰蓉包波兰种水", displayName: "水", amount: 50, unit: "g" },
      { name: "椰蓉包波兰种干酵母", displayName: "干酵母", amount: 0.7, unit: "g" },
      { name: "椰蓉包波兰种糖", displayName: "糖", amount: 7, unit: "g" },

      { type: "heading", text: "主面团" },
      { name: "椰蓉包高筋面粉", displayName: "高筋面粉", amount: 200, unit: "g" },
      { name: "椰蓉包牛奶", displayName: "牛奶", amount: 80, unit: "g" },
      { name: "椰蓉包奶粉", displayName: "奶粉", amount: 10, unit: "g" },
      { name: "椰蓉包盐", displayName: "盐", amount: 3, unit: "g" },
      { name: "椰蓉包糖", displayName: "糖", amount: 30, unit: "g" },
      { name: "椰蓉包干酵母", displayName: "干酵母", amount: 2, unit: "g" },
      { name: "椰蓉包全蛋液", displayName: "全蛋液", amount: 25, unit: "g" },
      { name: "椰蓉包黄油", displayName: "黄油", amount: 17, unit: "g" },

      { type: "heading", text: "椰蓉馅" },
      { name: "椰蓉馅黄油", displayName: "黄油", amount: 25, unit: "g" },
      { name: "椰蓉馅糖粉", displayName: "糖粉", amount: 25, unit: "g" },
      { name: "椰蓉馅全蛋液", displayName: "全蛋液", amount: 25, unit: "g" },
      { name: "椰蓉馅椰蓉", displayName: "椰蓉", amount: 50, unit: "g" },
      { name: "椰蓉馅牛奶", displayName: "牛奶", amount: 10, unit: "g" }
    ],
    steps: [
      "【椰蓉馅】",
      "{椰蓉馅黄油} 黄油融化。",
      "混入 {椰蓉馅糖粉} 糖粉和 {椰蓉馅全蛋液} 全蛋液。",
      "拌入 {椰蓉馅椰蓉} 椰蓉和 {椰蓉馅牛奶} 牛奶。",

      "【面团】",
      "将所有波兰种材料混合均匀。",
      "室温或冷藏发酵至表面有许多气泡，里面呈蜂窝状。",
      "波兰种与除 {椰蓉包黄油} 黄油外的主面团材料混合，2 档揉成团。",
      "换 4 档揉至扩展阶段。",
      "加入软化的黄油，1 档揉至黄油被面团吸收。",
      "换 4 档揉出手套膜。",
      "在温暖处发酵至两倍大。",
      "发酵完成后分成 9 份面团，每份约 50g，松弛 15 分钟。",

      "【整形与烘烤】",
      "小面团擀成长条，底部擀薄。",
      "均匀抹上约 15g 椰蓉馅，边缘留出少量空位。",
      "从上往下卷起，收口朝下。",
      "将面包卷从中间顺着切开，注意不要完全切断。",
      "将切面翻开并卷成花形，收口朝下放入模具。",
      "发酵至约两倍大。",
      "烤箱预热至 180°C。",
      "表面刷全蛋液。",
      "180°C 中下层烤约 18 分钟。",
      "出炉后震两下排出热气。",
      "脱模后冷却。"
    ]
  },

  "tz-cinnamon-rolls": {
    title: "汤种肉桂卷",
    name: "Tangzhong Cinnamon Rolls",
    image: "../images/tz-cinnamon-rolls.jpeg",
    imagePosition: "center center",
    imageZoom: 1,
    intro: "使用汤种制作的迷你肉桂卷，面包格外柔软，搭配红糖肉桂馅，香气浓郁。",
    ingredients: [
      { type: "heading", text: "汤种" },
      { name: "肉桂卷汤种中筋面粉", displayName: "中筋面粉", amount: 30, unit: "g" },
      { name: "肉桂卷汤种牛奶", displayName: "牛奶", amount: 130, unit: "g" },

      { type: "heading", text: "主面团" },
      { name: "肉桂卷高筋面粉", displayName: "高筋面粉", amount: 300, unit: "g" },
      { name: "肉桂卷牛奶", displayName: "牛奶", amount: 40, unit: "g" },
      { name: "肉桂卷盐", displayName: "盐", amount: 4, unit: "g" },
      { name: "肉桂卷糖", displayName: "糖", amount: 40, unit: "g" },
      { name: "肉桂卷干酵母", displayName: "干酵母", amount: 4, unit: "g" },
      { name: "肉桂卷蛋黄", displayName: "蛋黄", amount: 1, unit: "pc" },
      { name: "肉桂卷全蛋", displayName: "全蛋", amount: 1, unit: "pc" },
      { name: "肉桂卷无盐黄油", displayName: "无盐黄油", amount: 46, unit: "g" },
      { name: "改良剂", amount: 3, unit: "g" },

      { type: "heading", text: "红糖肉桂馅" },
      { name: "肉桂馅黄油", displayName: "黄油", amount: 75, unit: "g" },
      { name: "红糖", amount: 95, unit: "g" },
      { name: "肉桂粉", amount: 9, unit: "g" },
      { name: "香草精", amount: 0.5, unit: "tsp" }
    ],
    steps: [
      "【牛奶汤种】",
      "将 {肉桂卷汤种中筋面粉} 中筋面粉和 {肉桂卷汤种牛奶} 牛奶搅拌至无大颗粒。",
      "小火加热并不断搅拌。",
      "煮至呈很稠的蜂糊状。",
      "盛出并完全冷却后使用。",

      "【红糖肉桂馅】",
      "{肉桂馅黄油} 黄油打至顺滑。",
      "加入 {肉桂粉} 肉桂粉、{红糖} 红糖和 {香草精} 香草精。",
      "打发 2-3 分钟，至蓬松且颜色变浅。",
      "室温备用。",

      "【主面团】",
      "除 {肉桂卷无盐黄油} 黄油外，将汤种和所有主面团材料低速搅拌约 3 分钟至成团。",
      "转中速搅拌约 5 分钟，途中刮缸 1-2 次。",
      "加入软化的黄油，低速搅拌至黄油被面团吸收。",
      "转中速搅拌至能拉出薄膜。",
      "发酵至两倍大。",
      "将面团擀成约 40 × 52cm 的长方形。",
      "均匀抹上红糖肉桂馅。",
      "将面团上方 1/3 向下折叠，再将下方 1/3 向上折叠。",
      "整理成长方形并切掉两端。",
      "切出每条约 4cm 宽的长条，共 12 条。",
      "每条切两刀，切面朝上，编成三股辫子。",
      "尾部粘在一起收尾，再从下往上卷起。",
      "收口朝下放入马芬烤盘中。",
      "二次发酵至约 1.5 倍大。",
      "烤箱预热至 190°C。",
      "表面刷全蛋液。",
      "放中下层，190°C 烤约 16 分钟。",
      "在烤盘内冷却约 10 分钟后脱模。",
      "擀面时可以撒少量面粉防粘，最后两分钟注意观察上色情况。"
    ]
  },

  "tz-custard-buns": {
    title: "汤种卡仕达面包",
    name: "Tangzhong Custard Buns",
    image: "../images/tz-custard-buns.jpeg",
    imagePosition: "center 60%",
    imageZoom: 1,
    intro: "柔软的汤种面包包入香草卡仕达酱，做成小巧花形并以杏仁片装饰。",
    ingredients: [
      { type: "heading", text: "汤种" },
      { name: "卡仕达包汤种高筋面粉", displayName: "高筋面粉", amount: 20, unit: "g" },
      { name: "卡仕达包汤种冷水", displayName: "冷水", amount: 100, unit: "g" },

      { type: "heading", text: "主面团" },
      { name: "卡仕达包高筋面粉", displayName: "高筋面粉", amount: 250, unit: "g" },
      { name: "卡仕达包全蛋液", displayName: "全蛋液", amount: 35, unit: "g" },
      { name: "卡仕达包细砂糖", displayName: "细砂糖", amount: 30, unit: "g" },
      { name: "卡仕达包盐", displayName: "盐", amount: 2, unit: "g" },
      { name: "卡仕达包奶粉", displayName: "奶粉", amount: 7, unit: "g" },
      { name: "卡仕达包酵母", displayName: "酵母", amount: 3, unit: "g" },
      { name: "卡仕达包牛奶", displayName: "牛奶", amount: 55, unit: "g" },
      { name: "卡仕达包黄油", displayName: "黄油", amount: 20, unit: "g" },

      { type: "heading", text: "卡仕达酱" },
      { name: "卡仕达包蛋黄", displayName: "蛋黄", amount: 2, unit: "pc" },
      { name: "卡仕达酱糖", displayName: "糖", amount: 30, unit: "g" },
      { name: "卡仕达酱玉米淀粉", displayName: "玉米淀粉", amount: 15, unit: "g" },
      { name: "卡仕达酱香草精", displayName: "香草精", amount: 3, unit: "g" },
      { name: "卡仕达酱牛奶", displayName: "牛奶", amount: 200, unit: "g" }
    ],
    steps: [
      "【卡仕达酱】",
      "{卡仕达包蛋黄} 蛋黄和 {卡仕达酱糖} 糖搅拌至颜色变浅。",
      "筛入 {卡仕达酱玉米淀粉} 玉米淀粉并搅拌均匀。",
      "加入 {卡仕达酱香草精} 香草精。",
      "{卡仕达酱牛奶} 牛奶加热至沸腾。",
      "将热牛奶缓慢倒入蛋黄糊中，并不停搅拌。",
      "倒回锅中，小火加热至卡仕达酱非常浓稠。",
      "盛出后用保鲜膜贴面覆盖，冷藏备用。",

      "【汤种】",
      "{卡仕达包汤种高筋面粉} 高筋面粉和 {卡仕达包汤种冷水} 冷水混合。",
      "小火加热并搅拌至约 65°C，或变得很浓稠。",
      "盛出后冷藏至完全冷却。",

      "【主面团】",
      "除 {卡仕达包黄油} 黄油、盐和酵母外，将汤种和其他主面团材料放入面缸。",
      "低速揉至无干粉，冷藏松弛至少 1 小时或隔夜。",
      "加入酵母，揉至扩展阶段，能撑出较薄的膜。",
      "加入软化的黄油和盐，低速揉至黄油被吸收。",
      "转 4 档揉至完全阶段，能撑出手套膜。",
      "面团滚圆，在温暖处发酵至两倍大。",
      "取出排气并分成 9 份，滚圆后盖上保鲜膜，松弛 15 分钟。",

      "【整形与烘烤】",
      "桌面撒少量面粉防粘。",
      "面团轻轻拍扁，光面朝上，擀成长但不要太长的椭圆形。",
      "翻面后光面朝下。",
      "用勺子挖入约 25g 卡仕达酱，将面团对折并捏紧收口。",
      "在圆弧边缘剪出 3 个开口。",
      "放在温暖处发酵至约 1.5 倍大。",
      "烤箱预热至 180°C。",
      "表面刷全蛋液并撒上杏仁片。",
      "180°C 烤约 15 分钟。",
      "完全冷却后的卡仕达酱可以直接使用。"
    ]
  },

  "tz-chocolate-buns": {
    title: "汤种巧克力面包",
    name: "Tangzhong Chocolate Buns",
    image: "../images/tz-chocolate-buns.jpeg",
    imagePosition: "center center",
    imageZoom: 1,
    intro: "加入可可粉和黑巧克力豆的柔软汤种餐包，巧克力味浓郁，组织松软。",
    ingredients: [
      { type: "heading", text: "汤种" },
      { name: "巧克力包汤种高筋面粉", displayName: "高筋面粉", amount: 20, unit: "g" },
      { name: "巧克力包汤种冷水", displayName: "冷水", amount: 100, unit: "g" },

      { type: "heading", text: "主面团" },
      { name: "巧克力包高筋面粉", displayName: "高筋面粉", amount: 250, unit: "g" },
      { name: "可可粉", amount: 12, unit: "g" },
      { name: "巧克力包全蛋液", displayName: "全蛋液", amount: 35, unit: "g" },
      { name: "巧克力包细砂糖", displayName: "细砂糖", amount: 45, unit: "g" },
      { name: "巧克力包盐", displayName: "盐", amount: 2, unit: "g" },
      { name: "巧克力包奶粉", displayName: "奶粉", amount: 10, unit: "g" },
      { name: "巧克力包酵母", displayName: "酵母", amount: 3, unit: "g" },
      { name: "巧克力包水", displayName: "水", amount: 55, unit: "g" },
      { name: "巧克力包黄油", displayName: "黄油", amount: 20, unit: "g" },
      { name: "黑巧克力豆", amount: 40, unit: "g" }
    ],
    steps: [
      "【汤种】",
      "{巧克力包汤种高筋面粉} 高筋面粉和 {巧克力包汤种冷水} 冷水混合。",
      "小火加热并不断搅拌。",
      "煮至约 65°C，或变得很浓稠。",
      "盛出后冷藏至完全冷却。",

      "【主面团】",
      "除 {巧克力包黄油} 黄油、盐和酵母外，将汤种和其他主面团材料放入面缸。",
      "低速揉至无干粉，冷藏松弛至少 1 小时。",
      "加入酵母，揉至扩展阶段。",
      "加入软化的黄油和盐，揉至完全阶段。",
      "加入 {黑巧克力豆} 黑巧克力豆，低速混合均匀。",
      "面团滚圆并发酵至两倍大。",
      "将面团分成 16 份，松弛 15 分钟。",
      "桌面撒少量面粉防粘。",
      "面团轻轻拍扁，拍掉边缘气泡后滚圆。",
      "放入模具中，发酵至约两倍大。",
      "烤箱预热至 180°C。",
      "表面刷全蛋液。",
      "180°C 烤约 17 分钟。",
      "水量建议使用 55g；若面团偏干，可根据面粉吸水情况少量增加。"
    ]
  },
  "milk-dinner-rolls": {
    title: "奶油餐包",
    name: "Milk Dinner Rolls",
    image: "../images/milk-dinner-rolls.jpeg",
    imagePosition: "center center",
    imageZoom: 1,
    intro: "使用中种和淡奶油制作的迷你餐包，组织柔软细腻，奶香浓郁。",
    ingredients: [
      { type: "heading", text: "中种" },
      { name: "奶油餐包中种高筋面粉", displayName: "高筋面粉", amount: 125, unit: "g" },
      { name: "奶油餐包中种水", displayName: "水", amount: 77, unit: "g" },
      { name: "奶油餐包中种干酵母", displayName: "干酵母", amount: 1.5, unit: "g" },
      { name: "奶油餐包中种糖", displayName: "糖", amount: 5, unit: "g" },

      { type: "heading", text: "主面团" },
      { name: "奶油餐包高筋面粉", displayName: "高筋面粉", amount: 125, unit: "g" },
      { name: "奶油餐包淡奶油", displayName: "淡奶油", amount: 57, unit: "g" },
      { name: "奶油餐包奶粉", displayName: "奶粉", amount: 12, unit: "g" },
      { name: "奶油餐包盐", displayName: "盐", amount: 3, unit: "g" },
      { name: "奶油餐包糖", displayName: "糖", amount: 25, unit: "g" },
      { name: "奶油餐包干酵母", displayName: "干酵母", amount: 1, unit: "g" },
      { name: "奶油餐包全蛋液", displayName: "全蛋液", amount: 38, unit: "g" },
      { name: "奶油餐包黄油", displayName: "黄油", amount: 6, unit: "g" }
    ],
    steps: [
      "【前一晚准备】",
      "将所有中种材料混合并揉成团。",
      "室温发酵约半小时，再放入冰箱冷藏发酵一晚，24 小时内使用。",

      "【第二天】",
      "发酵好的中种面团底部应有丰富气孔，体积约为原来的 2-3 倍。",
      "将中种面团剪成小块，放入除 {奶油餐包黄油} 黄油外的主面团材料中。",
      "低速 1 档揉成团。",
      "转 4 档揉至能拉出较厚的膜。",
      "加入软化的黄油，1 档搅打均匀。",
      "转 4 档揉出手套膜。",
      "面团滚圆，发酵 30-40 分钟。",
      "分割成 12 份面团，醒发 20 分钟。",
      "轻轻拍扁并滚圆。",
      "放入模具中。",
      "在烤箱中放一碗热水，将面包发酵至两倍大。",
      "烤箱预热至 180°C。",
      "表面刷全蛋液。",
      "180°C 烤约 13 分钟，最后 3 分钟可开启热风功能。"
    ]
  },

  "red-bean-buns": {
    title: "中种红豆包",
    name: "Red Bean Buns",
    image: "../images/red-bean-buns.jpeg",
    imagePosition: "center center",
    imageZoom: 1,
    intro: "使用中种制作的柔软红豆包，每个面包装入香甜红豆馅，表面以芝麻装饰。",
    ingredients: [
      { type: "heading", text: "中种" },
      { name: "中种红豆包高筋面粉", displayName: "高筋面粉", amount: 175, unit: "g" },
      { name: "中种红豆包水", displayName: "水", amount: 105, unit: "g" },
      { name: "中种红豆包干酵母", displayName: "干酵母", amount: 1.5, unit: "g" },
      { name: "中种红豆包糖", displayName: "糖", amount: 7, unit: "g" },

      { type: "heading", text: "主面团" },
      { name: "红豆包高筋面粉", displayName: "高筋面粉", amount: 75, unit: "g" },
      { name: "红豆包牛奶", displayName: "牛奶", amount: 20, unit: "g" },
      { name: "红豆包奶粉", displayName: "奶粉", amount: 7, unit: "g" },
      { name: "红豆包盐", displayName: "盐", amount: 3, unit: "g" },
      { name: "红豆包糖", displayName: "糖", amount: 25, unit: "g" },
      { name: "红豆包干酵母", displayName: "干酵母", amount: 1, unit: "g" },
      { name: "红豆包全蛋液", displayName: "全蛋液", amount: 25, unit: "g" },
      { name: "红豆包黄油", displayName: "黄油", amount: 17, unit: "g" },
      { name: "芝麻", amount: 0, unit: "适量" },
      { name: "红豆馅", amount: 225, unit: "g" }
    ],
    steps: [
      "【前一晚准备】",
      "将所有中种材料混合并揉成团。",
      "室温发酵约半小时，再放入冰箱冷藏发酵一晚，24 小时内使用。",

      "【第二天】",
      "发酵好的中种面团底部应有丰富气孔，体积约为原来的 2-3 倍。",
      "将中种面团剪成小块，放入除 {红豆包黄油} 黄油外的主面团材料中。",
      "低速 1 档揉成团。",
      "转 4 档揉至能拉出较厚的膜。",
      "加入软化的黄油，1 档搅打均匀。",
      "转 4 档揉出手套膜。",
      "面团滚圆，发酵 30-40 分钟。",
      "分割成 9 份面团，每份约 50g，滚圆。",
      "若面团粘手，可撒少量面粉。",
      "面团醒发 15 分钟。",
      "将 {红豆馅} 红豆馅分成 9 份，每份约 25g，并搓成球形。",
      "醒发好的面团压扁，拍掉边缘气泡后滚圆。",
      "包入一份红豆馅，用虎口捏紧收口。",
      "收口朝下放在铺有油纸的烤盘上，并稍微压扁。",
      "在烤箱中放一碗热水，将面包发酵至约两倍大。",
      "烤箱预热至 180°C。",
      "表面刷全蛋液。",
      "擀面杖一端沾少量水和芝麻，再印在面包表面。",
      "180°C 烤约 13 分钟，最后 3 分钟可开启热风功能。"
    ]
  },

  "pineapple-buns": {
    title: "菠萝包",
    name: "Pineapple Buns",
    image: "../images/pineapple-buns.jpeg",
    imagePosition: "center 70%",
    imageZoom: 1,
    intro: "使用中种制作的柔软菠萝包，覆盖香甜酥脆的菠萝皮。",
    ingredients: [
      { type: "heading", text: "中种" },
      { name: "中种菠萝包高筋面粉", displayName: "高筋面粉", amount: 175, unit: "g" },
      { name: "中种菠萝包水", displayName: "水", amount: 105, unit: "g" },
      { name: "中种菠萝包干酵母", displayName: "干酵母", amount: 1.5, unit: "g" },
      { name: "中种菠萝包糖", displayName: "糖", amount: 7, unit: "g" },

      { type: "heading", text: "主面团" },
      { name: "中种菠萝包主面团高筋面粉", displayName: "高筋面粉", amount: 75, unit: "g" },
      { name: "中种菠萝包牛奶", displayName: "牛奶", amount: 20, unit: "g" },
      { name: "中种菠萝包奶粉", displayName: "奶粉", amount: 7, unit: "g" },
      { name: "中种菠萝包盐", displayName: "盐", amount: 3, unit: "g" },
      { name: "中种菠萝包糖", displayName: "糖", amount: 25, unit: "g" },
      { name: "中种菠萝包干酵母", displayName: "干酵母", amount: 1, unit: "g" },
      { name: "中种菠萝包全蛋液", displayName: "全蛋液", amount: 25, unit: "g" },
      { name: "中种菠萝包黄油", displayName: "黄油", amount: 17, unit: "g" },

      { type: "heading", text: "菠萝皮" },
      { name: "中种菠萝皮低筋面粉", displayName: "低筋面粉", amount: 90, unit: "g" },
      { name: "中种菠萝皮黄油", displayName: "黄油", amount: 45, unit: "g" },
      { name: "中种菠萝皮糖粉", displayName: "糖粉", amount: 40, unit: "g" },
      { name: "中种菠萝皮全蛋液", displayName: "全蛋液", amount: 20, unit: "g" },
      { name: "中种菠萝皮奶粉", displayName: "奶粉", amount: 9, unit: "g" },
      { name: "中种菠萝皮苏打粉", displayName: "苏打粉", amount: 0.5, unit: "g" },
      { name: "中种菠萝皮泡打粉", displayName: "泡打粉", amount: 1, unit: "g" }
    ],
    steps: [
      "【前一晚准备】",
      "将所有中种材料混合并揉成团。",
      "室温发酵约半小时，再放入冰箱冷藏发酵一晚，24 小时内使用。",
      "将 {中种菠萝皮黄油} 黄油软化，加入 {中种菠萝皮糖粉} 糖粉搅拌均匀。",
      "分两次加入 {中种菠萝皮全蛋液} 全蛋液，每次都搅拌均匀。",
      "筛入 {中种菠萝皮低筋面粉} 低筋面粉、{中种菠萝皮奶粉} 奶粉、{中种菠萝皮苏打粉} 苏打粉和 {中种菠萝皮泡打粉} 泡打粉。",
      "拌匀后用保鲜膜包裹并冷藏备用。",

      "【第二天】",
      "发酵好的中种面团底部应有丰富气孔，体积约为原来的 2-3 倍。",
      "将中种面团剪成小块，放入除 {中种菠萝包黄油} 黄油外的主面团材料中。",
      "低速 1 档揉成团。",
      "转 4 档揉至能拉出较厚的膜。",
      "加入软化的黄油，1 档搅打均匀。",
      "转 4 档揉出手套膜。",
      "面团滚圆，发酵 30-40 分钟。",
      "分割成 9 份面团，每份约 50g，滚圆后醒发 15 分钟。",
      "同时将菠萝皮分成 9 份，每份约 20g，冷藏备用。",
      "醒发好的面团压扁，拍掉边缘气泡后滚圆。",
      "将一份菠萝皮放在保鲜膜中，压至手掌大小。",
      "将菠萝皮盖在面团上，并用酥皮印压出花纹。",
      "烤箱中放一碗热水，将面包发酵至约两倍大。",
      "烤箱预热至 180°C。",
      "表面刷全蛋液。",
      "180°C 烤约 13 分钟，最后 3 分钟可开启热风功能。"
    ]
  },

  "cinnamon-rolls": {
    title: "美式肉桂卷",
    name: " Cinnamon Rolls",
    image: "../images/cinnamon-rolls.jpeg",
    imagePosition: "center center",
    imageZoom: 1,
    intro: "柔软面包卷入红糖肉桂馅和坚果，烘烤后抹上轻盈奶油奶酪糖霜。",
    ingredients: [
      { type: "heading", text: "面团" },
      { name: "美式肉桂卷中筋面粉", displayName: "中筋面粉", amount: 300, unit: "g" },
      { name: "美式肉桂卷水", displayName: "水", amount: 115, unit: "g" },
      { name: "美式肉桂卷干酵母", displayName: "干酵母", amount: 4, unit: "g" },
      { name: "美式肉桂卷糖", displayName: "糖", amount: 25, unit: "g" },
      { name: "美式肉桂卷牛奶", displayName: "牛奶", amount: 65, unit: "g" },
      { name: "美式肉桂卷黄油", displayName: "黄油", amount: 12, unit: "g" },

      { type: "heading", text: "肉桂馅" },
      { name: "美式肉桂馅黄油", displayName: "黄油", amount: 50, unit: "g" },
      { name: "黄糖", amount: 40, unit: "g" },
      { name: "美式肉桂粉", displayName: "肉桂粉", amount: 10, unit: "g" },
      { name: "烤过的坚果", amount: 20, unit: "g" },

      { type: "heading", text: "糖霜" },
      { name: "糖霜黄油", displayName: "黄油", amount: 10, unit: "g" },
      { name: "奶油奶酪", amount: 10, unit: "g" },
      { name: "糖粉", amount: 50, unit: "g" },
      { name: "香草精", amount: 3, unit: "g" },
      { name: "糖霜牛奶", displayName: "牛奶", amount: 3, unit: "tsp" }
    ],
    steps: [
      "【面团】",
      "除 {美式肉桂卷黄油} 黄油外，将所有面团材料放入搅拌缸中。",
      "低速 2 档揉成团，再转 4 档揉出较薄的膜。",
      "加入软化的黄油，1 档揉至黄油被面团吸收。",
      "转 4 档揉至均匀而透光的薄膜，破口边缘呈锯齿状即可。",
      "面团滚圆并盖上保鲜膜，在温暖处发酵约 1 小时 10 分钟。",
      "手指蘸面粉在面团中间戳洞，洞口不回缩代表发酵完成。",
      "取出面团排气、滚圆，松弛 20 分钟。",

      "【肉桂馅】",
      "若 {黄糖} 黄糖有结块，先将其捏碎。",
      "加入 {美式肉桂粉} 肉桂粉，混合均匀。",
      "加入软化的 {美式肉桂馅黄油} 黄油，搅拌均匀。",

      "【整形与烘烤】",
      "桌面撒少量面粉防粘。",
      "将松弛好的面团擀成长方形薄片，厚度约 5mm。",
      "其中一边擀薄。",
      "均匀抹上肉桂馅，在擀薄的一端留出约 1cm。",
      "撒上 {烤过的坚果} 烤过的坚果。",
      "轻轻卷起面团。",
      "分割成 9 或 10 份，放在垫有烘焙纸的烤盘上。",
      "二次发酵约 40 分钟。",
      "烤箱预热至 190°C。",
      "190°C 烤约 15-20 分钟。",

      "【糖霜】",
      "将 {糖霜黄油} 黄油和 {奶油奶酪} 奶油奶酪放入碗中。",
      "微波炉每次加热 10 秒，直到软化。",
      "搅拌至顺滑。",
      "加入 {糖粉} 糖粉和 {香草精} 香草精，搅拌均匀。",
      "最后拌入 {糖霜牛奶} 牛奶。",
      "趁肉桂卷仍温热时，在表面抹上少量糖霜。"
    ]
  },

  "salt-bread": {
    title: "盐面包",
    name: "Salt Bread",
    image: "../images/salt-bread.jpeg",
    imagePosition: "center center",
    imageZoom: 1,
    intro: "法国老面",
    ingredients: [
      { type: "heading", text: "法国老面" },
      { name: "盐面包老面中筋面粉", displayName: "中筋面粉", amount: 100, unit: "g" },
      { name: "盐面包老面水", displayName: "水", amount: 68, unit: "g" },
      { name: "盐面包老面干酵母", displayName: "干酵母", amount: 1, unit: "g" },
      { name: "盐面包老面盐", displayName: "盐", amount: 2, unit: "g" },

      { type: "heading", text: "主面团" },
      { name: "盐面包高筋面粉", displayName: "高筋面粉", amount: 200, unit: "g" },
      { name: "盐面包低筋面粉", displayName: "低筋面粉", amount: 50, unit: "g" },
      { name: "法国老面", amount: 40, unit: "g" },
      { name: "盐面包奶粉", displayName: "奶粉", amount: 11, unit: "g" },
      { name: "盐面包盐", displayName: "盐", amount: 4, unit: "g" },
      { name: "盐面包糖", displayName: "糖", amount: 30, unit: "g" },
      { name: "盐面包干酵母", displayName: "干酵母", amount: 3, unit: "g" },
      { name: "盐面包全蛋液", displayName: "全蛋液", amount: 15, unit: "g" },
      { name: "盐面包冷水", displayName: "冷水", amount: 122, unit: "g" },
      { name: "盐面包无盐黄油", displayName: "无盐黄油", amount: 20, unit: "g" },
      { name: "有盐黄油", amount: 8, unit: "pc" }
    ],
    steps: [
      "【法国老面】",
      "将 {盐面包老面中筋面粉} 中筋面粉、{盐面包老面水} 水、{盐面包老面干酵母} 干酵母和 {盐面包老面盐} 盐揉成团。",
      "室温发酵约半小时，再冷藏发酵 12-16 小时。",
      "三天内使用，也可以分成 4 份冷冻保存。",
      "发酵好的老面内部应有丰富气孔。",

      "【主面团】",
      "除 {盐面包无盐黄油} 无盐黄油外，将所有主面团材料低速揉成团。",
      "转中速揉出较厚的膜。",
      "加入软化的无盐黄油，低速揉均匀。",
      "转高速揉出薄膜。",
      "面团发酵至两倍大。",
      "分割成 8 份，每份约 60g。",
      "搓成水滴状，松弛 15 分钟。",
      "将面团从中间往上和往下擀成约 40cm 长的三角形。",
      "在宽端放入一块约 6g 的有盐黄油。",
      "从宽端卷起，收口朝下。",
      "烤箱发酵 40 分钟，再室温发酵约 30 分钟。",

      "【蒸汽烘烤】",
      "发酵 40 分钟后，在烤箱底部放入铸铁锅，并预热至 230°C 约 30 分钟。",
      "面包表面喷水并撒盐。",
      "戴上手套，将面包送入烤箱。",
      "往铸铁锅中倒入约 200ml 热水制造蒸汽，并马上关门。",
      "关掉烤箱焖约 3 分钟后并取出铸铁锅。",
      "将温度降至 220°C 烤约 7 分钟。",
      "再以 200°C 热风烤约 3 分钟。"
    ]
  },

  "donuts": {
    title: "卡仕达甜甜圈",
    name: "Custard Donuts",
    image: "../images/donuts.png",
    imagePosition: "center center",
    imageZoom: 1,
    intro: "松软油炸甜甜圈裹上细砂糖，并分别挤入香草卡仕达或抹茶卡仕达。",
    ingredients: [
      { type: "heading", text: "面团" },
      { name: "卡仕达甜甜圈高筋面粉", displayName: "高筋面粉", amount: 175, unit: "g" },
      { name: "卡仕达甜甜圈低筋面粉", displayName: "低筋面粉", amount: 75, unit: "g" },
      { name: "卡仕达甜甜圈干酵母", displayName: "干酵母", amount: 3, unit: "g" },
      { name: "卡仕达甜甜圈糖", displayName: "糖", amount: 35, unit: "g" },
      { name: "卡仕达甜甜圈盐", displayName: "盐", amount: 3, unit: "g" },
      { name: "卡仕达甜甜圈牛奶", displayName: "牛奶", amount: 110, unit: "g" },
      { name: "卡仕达甜甜圈鸡蛋", displayName: "鸡蛋", amount: 1, unit: "pc" },
      { name: "卡仕达甜甜圈黄油", displayName: "黄油", amount: 22, unit: "g" },

      { type: "heading", text: "香草卡仕达" },
      { name: "香草卡仕达蛋黄", displayName: "蛋黄", amount: 1.5, unit: "pc" },
      { name: "香草卡仕达糖", displayName: "糖", amount: 15, unit: "g" },
      { name: "香草卡仕达玉米淀粉", displayName: "玉米淀粉", amount: 11, unit: "g" },
      { name: "香草卡仕达牛奶", displayName: "牛奶", amount: 150, unit: "g" },
      { name: "香草精", amount: 0, unit: "适量" },

      { type: "heading", text: "抹茶卡仕达" },
      { name: "抹茶卡仕达蛋黄", displayName: "蛋黄", amount: 1.5, unit: "pc" },
      { name: "抹茶卡仕达糖", displayName: "糖", amount: 15, unit: "g" },
      { name: "抹茶卡仕达玉米淀粉", displayName: "玉米淀粉", amount: 11, unit: "g" },
      { name: "抹茶粉", amount: 2, unit: "g" },
      { name: "抹茶卡仕达牛奶", displayName: "牛奶", amount: 150, unit: "g" }
    ],
    steps: [
      "【卡仕达酱】",
      "香草口味：将 {香草卡仕达蛋黄} 蛋黄和 {香草卡仕达糖} 糖搅拌至发白。",
      "筛入 {香草卡仕达玉米淀粉} 玉米淀粉，加入香草精。",
      "{香草卡仕达牛奶} 牛奶加热至冒小泡。",
      "少量多次倒入蛋黄糊，混合后倒回锅中。",
      "小火加热并不断搅拌至浓稠，冒泡后关火。",
      "抹茶口味：将 {抹茶粉} 抹茶粉和 {抹茶卡仕达玉米淀粉} 玉米淀粉一起筛入蛋黄糊。",
      "按照同样方法，加入 {抹茶卡仕达牛奶} 牛奶煮成浓稠卡仕达。",
      "卡仕达盛出后用保鲜膜贴面覆盖，冷藏备用。",

      "【面团】",
      "除 {卡仕达甜甜圈黄油} 黄油外，将所有面团材料揉成光滑面团。",
      "加入室温软化的黄油，继续揉至能拉出薄膜。",
      "发酵至两倍大。",
      "分割成 8 或 9 份，滚圆并松弛 15 分钟。",
      "面团拍扁排气，再次滚圆。",
      "收口朝下放在烘焙纸上。",
      "发酵约 1 小时，至约两倍大。",

      "【油炸与填馅】",
      "油加热至 170°C。",
      "连着烘焙纸将面团放入油锅。",
      "几秒后轻轻取走油纸。",
      "每面炸约 2 分钟，至金黄色。",
      "取出后放在厨房纸上沥干。",
      "表面裹上一层细砂糖。",
      "用小刀从甜甜圈侧面插入，并在里面左右切一下形成空洞。",
      "冷藏后的卡仕达用刮刀翻拌至顺滑。",
      "装入裱花袋中，挤入甜甜圈。"
    ]
  }
});

