Object.assign(recipes, {
  "biscoff-white-chocolate-cookies": {
    title: "Biscoff白巧软曲奇",
    name: "Biscoff White Chocolate Cookies",
    image: "../images/biscoff-cookies.png",
    imagePosition: "center center",
    imageZoom: 1,
    intro: "",
    ingredients: [
      { name: "Biscoff白巧软曲奇黄油", displayName: "黄油", amount: 115, unit: "g" },
      { name: "Biscoff白巧软曲奇黄糖", displayName: "黄糖", amount: 60, unit: "g" },
      { name: "Biscoff白巧软曲奇白糖", displayName: "白糖", amount: 45, unit: "g" },
      { name: "Biscoff白巧软曲奇盐", displayName: "盐", amount: 1, unit: "g" },
      { name: "Biscoff白巧软曲奇鸡蛋", displayName: "鸡蛋", amount: 1, unit: "pc" },
      { name: "Biscoff白巧软曲奇中粉", displayName: "中粉", amount: 175, unit: "g" },
      { name: "Biscoff白巧软曲奇玉米淀粉", displayName: "玉米淀粉", amount: 7, unit: "g" },
      { name: "Biscoff白巧软曲奇小苏打", displayName: "小苏打", amount: 2, unit: "g" },
      { name: "Biscoff白巧软曲奇泡打粉", displayName: "泡打粉", amount: 1, unit: "g" },
      { name: "Biscoff白巧软曲奇香草膏", displayName: "香草膏", amount: 2, unit: "g" },
      { name: "Biscoff白巧软曲奇白巧面团", displayName: "白巧（面团）", amount: 80, unit: "g" },
      { name: "Biscoff白巧软曲奇白巧装饰", displayName: "白巧（装饰）", amount: 20, unit: "g" },
      { name: "Biscoff白巧软曲奇饼干面团", displayName: "Biscoff（面团）", amount: 8, unit: "pc" },
      { name: "Biscoff白巧软曲奇饼干装饰", displayName: "Biscoff（装饰）", amount: 2, unit: "pc" },
    ],
    steps: [
      "白巧克力切成小块。",
      "微波炉软化 {Biscoff白巧软曲奇黄油} 黄油。",
      "倒入 {Biscoff白巧软曲奇黄糖} 黄糖、{Biscoff白巧软曲奇白糖} 白糖和 {Biscoff白巧软曲奇盐} 盐。",
      "打蛋器低速搅打均匀。",
      "加入 {Biscoff白巧软曲奇鸡蛋} 鸡蛋和 {Biscoff白巧软曲奇香草膏} 香草膏。",
      "低速搅拌均匀。",
      "混合 {Biscoff白巧软曲奇中粉} 中粉、{Biscoff白巧软曲奇玉米淀粉} 玉米淀粉、{Biscoff白巧软曲奇小苏打} 小苏打和 {Biscoff白巧软曲奇泡打粉} 泡打粉。",
      "过筛到面糊中。",
      "用刮刀拌至剩下一点点干粉。",
      "拌入 {Biscoff白巧软曲奇白巧面团} 白巧和 {Biscoff白巧软曲奇饼干面团} Biscoff。",
      "冷藏至少一小时。",
      "烤箱预热 170°C。",
      "分成 14 等份，每份约 41g。",
      "面团之间要留足够的空间。",
      "稍微摁扁。",
      "放上 {Biscoff白巧软曲奇白巧装饰} 白巧和 {Biscoff白巧软曲奇饼干装饰} Biscoff 装饰。",
      "180°C 中层烤 8-10 分钟。",
      "出炉后的曲奇非常软，先不要碰。",
      "放一会儿等变硬一点，再放在烤网上冷却。",
      "Tips：巧克力可以用普通巧克力，也可以用巧克力豆。",
      "第二天微波炉转 30 秒会超级好吃。",
    ],
  },

  "hojicha-biscoff-cookies": {
    title: "Biscoff白巧软曲奇",
    name: "Hojicha White Chocolate Biscoff Cookies",
    image: "../images/hojicha-biscoff-cookies.jpeg",
    imagePosition: "center center",
    imageZoom: 1,
    intro: "",
    ingredients: [
      { name: "焙茶Biscoff黄油", displayName: "黄油", amount: 115, unit: "g" },
      { name: "焙茶Biscoff黄糖", displayName: "黄糖", amount: 65, unit: "g" },
      { name: "焙茶Biscoff白糖", displayName: "白糖", amount: 50, unit: "g" },
      { name: "焙茶Biscoff盐", displayName: "盐", amount: 1, unit: "g" },
      { name: "焙茶Biscoff鸡蛋", displayName: "鸡蛋", amount: 1, unit: "pc" },
      { name: "焙茶Biscoff中粉", displayName: "中粉", amount: 180, unit: "g" },
      { name: "焙茶Biscoff焙茶粉", displayName: "焙茶粉", amount: 12, unit: "g" },
      { name: "焙茶Biscoff小苏打", displayName: "小苏打", amount: 2, unit: "g" },
      { name: "焙茶Biscoff泡打粉", displayName: "泡打粉", amount: 1, unit: "g" },
      { name: "焙茶Biscoff香草膏", displayName: "香草膏", amount: 2, unit: "g" },
      { name: "焙茶Biscoff白巧面团", displayName: "白巧（面团）", amount: 80, unit: "g" },
      { name: "焙茶Biscoff白巧装饰", displayName: "白巧（装饰）", amount: 20, unit: "g" },
      { name: "焙茶Biscoff饼干面团", displayName: "Biscoff（面团）", amount: 8, unit: "pc" },
      { name: "焙茶Biscoff饼干装饰", displayName: "Biscoff（装饰）", amount: 2, unit: "pc" },
    ],
    steps: [
      "室温软化 {焙茶Biscoff黄油} 黄油。",
      "倒入 {焙茶Biscoff黄糖} 黄糖、{焙茶Biscoff白糖} 白糖和 {焙茶Biscoff盐} 盐，打蛋器低速搅打均匀。",
      "加入 {焙茶Biscoff鸡蛋} 鸡蛋和 {焙茶Biscoff香草膏} 香草膏，低速搅拌均匀。",
      "混合 {焙茶Biscoff中粉} 中粉、{焙茶Biscoff焙茶粉} 焙茶粉、{焙茶Biscoff小苏打} 小苏打和 {焙茶Biscoff泡打粉} 泡打粉。",
      "过筛到面糊中。",
      "用刮刀拌至剩下一点点干粉。",
      "拌入 {焙茶Biscoff白巧面团} 白巧和 {焙茶Biscoff饼干面团} Biscoff 饼干碎。",
      "面团冷藏至少一小时。",
      "烤箱预热 180°C。",
      "分成 14 等份。",
      "面团之间要留足够的空间。",
      "稍微摁扁，放上 {焙茶Biscoff白巧装饰} 白巧和 {焙茶Biscoff饼干装饰} Biscoff 装饰。",
      "180°C 中层烤 8-10 分钟。",
      "出炉后的曲奇非常软，先不要碰。",
      "放一会儿等变硬一点，再放在烤网上冷却。",
    ],
  },

  "matcha-soft-cookies": {
    title: "抹茶软曲奇",
    name: "Matcha Soft Cookies",
    image: "../images/matcha-cookies.jpeg",
    imagePosition: "center center",
    imageZoom: 1,
    intro: "",
    ingredients: [
      { name: "抹茶软曲奇黄油", displayName: "黄油", amount: 130, unit: "g" },
      { name: "抹茶软曲奇黄糖", displayName: "黄糖", amount: 74, unit: "g" },
      { name: "抹茶软曲奇白糖", displayName: "白糖", amount: 56, unit: "g" },
      { name: "抹茶软曲奇盐", displayName: "盐", amount: 1, unit: "g" },
      { name: "抹茶软曲奇鸡蛋", displayName: "鸡蛋", amount: 1, unit: "pc" },
      { name: "抹茶软曲奇中粉", displayName: "中粉", amount: 163, unit: "g" },
      { name: "抹茶软曲奇抹茶粉", displayName: "抹茶粉", amount: 12, unit: "g" },
      { name: "抹茶软曲奇玉米淀粉", displayName: "玉米淀粉", amount: 7, unit: "g" },
      { name: "抹茶软曲奇小苏打", displayName: "小苏打", amount: 2, unit: "g" },
      { name: "抹茶软曲奇香草膏", displayName: "香草膏", amount: 2, unit: "g" },
      { name: "抹茶软曲奇白巧面团", displayName: "白巧（面团）", amount: 80, unit: "g" },
      { name: "抹茶软曲奇白巧装饰", displayName: "白巧（装饰）", amount: 20, unit: "g" },
    ],
    steps: [
      "白巧克力切成小块。",
      "微波炉软化 {抹茶软曲奇黄油} 黄油。",
      "倒入 {抹茶软曲奇黄糖} 黄糖、{抹茶软曲奇白糖} 白糖和 {抹茶软曲奇盐} 盐。",
      "打蛋器低速搅打均匀。",
      "加入 {抹茶软曲奇鸡蛋} 鸡蛋和 {抹茶软曲奇香草膏} 香草膏。",
      "低速搅拌均匀。",
      "混合 {抹茶软曲奇中粉} 中粉、{抹茶软曲奇抹茶粉} 抹茶粉、{抹茶软曲奇玉米淀粉} 玉米淀粉和 {抹茶软曲奇小苏打} 小苏打。",
      "过筛到面糊中。",
      "用刮刀拌至剩下一点点干粉。",
      "可以分成两份，一半白巧一半黑巧，也可以全部都放同一种。",
      "冷藏至少一小时。",
      "烤箱预热 170°C。",
      "分成 12 或 13 等份放在烤盘上。",
      "面团之间要留足够的空间。",
      "稍微摁扁约 2.5cm 厚。",
      "放上 {抹茶软曲奇白巧装饰} 巧克力装饰。",
      "170°C 中层烤 10-13 分钟。",
      "出炉后的曲奇非常软，先不要碰。",
      "放一会儿等变硬一点，再放在烤网上冷却。",
      "Tips：冷藏面团可以让曲奇烤出来更厚，味道更融合。",
      "巧克力可以用普通巧克力，也可以用巧克力豆。",
      "第二天微波炉转 30 秒会超级好吃。",
    ],
  },

  "almond-cookies": {
    title: "杏仁酥",
    name: "Almond Cookies",
    image: "../images/almond-cookies.jpeg",
    imagePosition: "center center",
    imageZoom: 1,
    intro: "",
    ingredients: [
      { name: "杏仁酥猪油", displayName: "猪油", amount: 97, unit: "g" },
      { name: "杏仁酥砂糖", displayName: "砂糖", amount: 60, unit: "g" },
      { name: "杏仁酥盐", displayName: "盐", amount: 1, unit: "g" },
      { name: "杏仁酥全蛋液", displayName: "全蛋液", amount: 35, unit: "g" },
      { name: "杏仁酥低粉", displayName: "低粉", amount: 145, unit: "g" },
      { name: "杏仁酥杏仁粉", displayName: "杏仁粉", amount: 52, unit: "g" },
      { name: "杏仁酥泡打粉", displayName: "泡打粉", amount: 2.5, unit: "g" },
      { name: "杏仁酥小苏打", displayName: "小苏打", amount: 1, unit: "g" },
      { name: "杏仁酥蛋黄", displayName: "蛋黄", amount: 1, unit: "g" },
      { name: "杏仁片", amount: 0, unit: "适量" },
    ],
    steps: [
      "{杏仁酥猪油} 猪油室温软化。",
      "加入 {杏仁酥砂糖} 砂糖和 {杏仁酥盐} 盐，用蛋抽打发至膨大。",
      "加入 {杏仁酥全蛋液} 全蛋液抽打。",
      "筛入 {杏仁酥低粉} 低粉、{杏仁酥杏仁粉} 杏仁粉、{杏仁酥泡打粉} 泡打粉和 {杏仁酥小苏打} 小苏打。",
      "用刮刀拌成团。",
      "分成 28 个，每个约 14g。",
      "中间稍微按扁。",
      "{杏仁酥蛋黄} 蛋黄加几滴水，这样容易刷一点。",
      "表面刷 2-3 层蛋黄液。",
      "放上杏仁片。",
      "175°C 烤 20 分钟，焖 10 分钟取出。",
    ],
  },

  "coconut-cookies": {
    title: "椰香饼干",
    name: "Coconut Shortbread",
    image: "../images/coconut-cookies.jpeg",
    imagePosition: "center center",
    imageZoom: 1,
    intro:
      "这是一款外表很朴素的无蛋饼干，类似于 walker 的英式奶油酥饼。充满了黄油的香气，添加了椰蓉让味道更有层次。材料和做法都很简单。配方来自 youtuber: Old-fashioned bakery",
    ingredients: [
      { name: "椰香饼干黄油", displayName: "黄油", amount: 180, unit: "g" },
      { name: "椰香饼干盐", displayName: "盐", amount: 1, unit: "g" },
      { name: "椰香饼干糖", displayName: "糖", amount: 90, unit: "g" },
      { name: "椰香饼干奶粉", displayName: "奶粉", amount: 10, unit: "g" },
      { name: "椰香饼干香草膏", displayName: "香草膏", amount: 3, unit: "g" },
      { name: "椰香饼干低粉", displayName: "低粉", amount: 270, unit: "g" },
      { name: "椰蓉", amount: 40, unit: "g" },
    ],
    steps: [
      "{椰香饼干黄油} 黄油室温软化。",
      "加入 {椰香饼干盐} 盐和 {椰香饼干糖} 糖，低速搅拌均匀。",
      "加入 {椰香饼干奶粉} 奶粉和 {椰香饼干香草膏} 香草膏，低速混合。",
      "拌入 {椰香饼干低粉} 低粉和 {椰蓉} 椰蓉至无干粉。",
      "倒入 20x20cm 的方形模具中（已垫烘焙纸）。",
      "用刮刀压紧实、平整。",
      "冷藏至少 1 小时。",
      "切出 18 块饼干。",
      "表面戳洞。",
      "撒上一些细砂糖和椰蓉。",
      "烤箱预热 150°C。",
      "150°C 烤 20 分钟，140°C 再烤 15 分钟。",
    ],
  },

  "lemon-curd-cookies": {
    title: "柠檬凝乳曲奇",
    name: "Lemon Curd Cookies",
    image: "../images/lemon-curd-cookies.jpeg",
    imagePosition: "center center",
    imageZoom: 1,
    intro: "参考了 cooking tree 的食谱，份量减半。曲奇口感外皮是带点酥脆的，内心是软的。",
    ingredients: [
      { type: "heading", text: "柠檬凝乳" },
      { name: "柠檬凝乳蛋黄", displayName: "蛋黄", amount: 1, unit: "pc" },
      { name: "柠檬凝乳细砂糖", displayName: "细砂糖", amount: 20, unit: "g" },
      { name: "柠檬凝乳盐", displayName: "盐", amount: 1, unit: "g" },
      { name: "柠檬凝乳玉米淀粉", displayName: "玉米淀粉", amount: 4, unit: "g" },
      { name: "柠檬凝乳牛奶", displayName: "牛奶", amount: 20, unit: "g" },
      { name: "柠檬凝乳柠檬汁", displayName: "柠檬汁", amount: 20, unit: "g" },
      { name: "柠檬凝乳无盐黄油", displayName: "无盐黄油", amount: 10, unit: "g" },

      { type: "heading", text: "曲奇" },
      { name: "柠檬曲奇细砂糖", displayName: "细砂糖", amount: 65, unit: "g" },
      { name: "柠檬曲奇盐", displayName: "盐", amount: 1, unit: "g" },
      { name: "柠檬曲奇柠檬皮屑", displayName: "柠檬皮屑", amount: 1, unit: "pc" },
      { name: "柠檬曲奇无盐黄油", displayName: "无盐黄油", amount: 40, unit: "g" },
      { name: "柠檬曲奇香草膏", displayName: "香草膏", amount: 0.25, unit: "tsp" },
      { name: "柠檬曲奇柠檬汁", displayName: "柠檬汁", amount: 7, unit: "g" },
      { name: "柠檬曲奇鸡蛋", displayName: "鸡蛋", amount: 1, unit: "g" },
      { name: "柠檬曲奇低粉", displayName: "低粉", amount: 150, unit: "g" },
      { name: "柠檬曲奇泡打粉", displayName: "泡打粉", amount: 2.5, unit: "g" },
    ],
    steps: [
      "【曲奇面团】",
      "用擦板把 {柠檬曲奇柠檬皮屑} 柠檬的皮擦下来。",
      "挤一个柠檬汁备用。",
      "把 3/5 的柠檬皮屑与 {柠檬曲奇细砂糖} 糖和 {柠檬曲奇盐} 盐混合。",
      "倒入融化的 {柠檬曲奇无盐黄油} 黄油、{柠檬曲奇香草膏} 香草膏和 {柠檬曲奇柠檬汁} 柠檬汁。",
      "打入一个室温的 {柠檬曲奇鸡蛋} 鸡蛋搅匀。",
      "筛入 {柠檬曲奇低粉} 面粉和 {柠檬曲奇泡打粉} 泡打粉。",
      "用刮刀拌至无干粉。",
      "面团密封冷藏 1 小时。",
      "【柠檬凝乳】",
      "{柠檬凝乳蛋黄} 蛋黄、{柠檬凝乳细砂糖} 糖和 {柠檬凝乳盐} 盐搅拌至发白。",
      "加入 {柠檬凝乳玉米淀粉} 玉米淀粉搅匀。",
      "倒入剩下的柠檬皮屑、{柠檬凝乳柠檬汁} 柠檬汁和 {柠檬凝乳牛奶} 牛奶混合均匀。",
      "小火不停搅拌加热至浓稠。",
      "关火混入 {柠檬凝乳无盐黄油} 黄油。",
      "盛出冷却备用。",
      "【烤制曲奇】",
      "烤箱预热 185°C。",
      "冷藏后的面团 15g 一个，大约 20 份。",
      "搓圆后在糖粉中滚一圈，让面团裹上一层糖粉。",
      "用一个小勺把中间按扁。",
      "烤箱 165°C 烤 12 分钟。",
      "出炉后马上再用小勺把曲奇中间按压一下。",
      "曲奇冷却后中间挤上柠檬凝乳。",
    ],
  },

  "diamond-cookies": {
    title: "钻石曲奇 / 厚烧奶油酥饼",
    name: "Diamond Cookies",
    image: "../images/diamond-cookies.jpeg",
    imagePosition: "center center",
    imageZoom: 1,
    intro: "配方来自巧儿灶咖",
    ingredients: [
      { type: "heading", text: "香草味" },
      { name: "香草钻石曲奇无盐黄油", displayName: "无盐黄油", amount: 100, unit: "g" },
      { name: "香草钻石曲奇淡奶油", displayName: "淡奶油", amount: 2, unit: "tsp" },
      { name: "香草钻石曲奇香草膏", displayName: "香草膏", amount: 0.5, unit: "tsp" },
      { name: "香草钻石曲奇杏仁粉", displayName: "杏仁粉", amount: 30, unit: "g" },
      { name: "香草钻石曲奇高筋面粉", displayName: "高筋面粉", amount: 70, unit: "g" },
      { name: "香草钻石曲奇低筋面粉", displayName: "低筋面粉", amount: 30, unit: "g" },
      { name: "香草钻石曲奇糖粉", displayName: "糖粉", amount: 40, unit: "g" },
      { name: "香草钻石曲奇海盐", displayName: "海盐", amount: 1, unit: "g" },

      { type: "heading", text: "伯爵红茶" },
      { name: "伯爵钻石曲奇无盐黄油", displayName: "无盐黄油", amount: 100, unit: "g" },
      { name: "伯爵钻石曲奇淡奶油", displayName: "淡奶油", amount: 2, unit: "tsp" },
      { name: "伯爵钻石曲奇杏仁粉", displayName: "杏仁粉", amount: 30, unit: "g" },
      { name: "伯爵钻石曲奇高筋面粉", displayName: "高筋面粉", amount: 67, unit: "g" },
      { name: "伯爵钻石曲奇低筋面粉", displayName: "低筋面粉", amount: 30, unit: "g" },
      { name: "伯爵钻石曲奇糖粉", displayName: "糖粉", amount: 40, unit: "g" },
      { name: "伯爵钻石曲奇海盐", displayName: "海盐", amount: 1, unit: "g" },
      { name: "伯爵红茶", amount: 4, unit: "g" },
    ],
    steps: [
      "杏仁粉、高筋面粉、低筋面粉、糖粉、盐和茶粉冷冻 30 分钟以上。",
      "黄油切小块，淡奶油、香草膏冷藏 30 分钟以上。",
      "粉类在料理机里打 30 秒混合均匀。",
      "倒入黄油，打至成团（约一分钟）。",
      "面团在保鲜膜上来回揉几下，揉成圆柱体（直径约 4 厘米）。",
      "包在烘焙纸里面，两头扭紧。",
      "冷冻至少 2 小时。",
      "切成 1.5cm 的厚片，边缘沾上细砂糖。",
      "160°C 烤 13 分钟，170°C 烤 10 分钟。",
    ],
  },
});
